ix: csharp: Using dependency management / partOfProperty to render optional types with question mark
asyncapi/modelina pull request #1051
Opened 2022-12-08 20:35 UTC by zaytsevand

**Description**

- Using ConstrainedObjectPropertyModel to get info on if the property is required

**Related issue(s)**
Fixes #941

2022-12-08 20:43 UTC, zaytsevand commented
@jonaslagoni I don't get what's wrong here, but black-box tests are constantly failing

2022-12-08 21:19 UTC, jonaslagoni requested changes
My comment fixes your blackbox tests and the linter you can probably fix with `npm run lint:fix`

2022-12-08 21:19 UTC, jonaslagoni commented on src/generators/csharp/CSharpConstrainer.ts
>  import { ConstrainedEnumValueModel } from '../../models';
```suggestion
import { ConstrainedEnumValueModel, ConstrainedObjectPropertyModel } from '../../models';
```

2022-12-16 19:14 UTC, jonaslagoni approved these changes
LGTM 🔥

2022-12-16 19:14 UTC, jonaslagoni commented
/rtm

2022-12-16 19:14 UTC, merged