feat: adding interpreter options override
asyncapi/modelina pull request #1071
Opened 2022-12-29 13:08 UTC by artur-ciocanu

**Description**
This is an enhancement that would allow anyone to override default interpreter behavior. Some of use cases are overriding default behavior of `additionalProperties`, `additionalItems` that would allow anyone to customize how these schema properties are handled. For example by default these properties are treated as `true`, however we might want to treat them as `false` during code gen.

A typical example using interpreter options would look like this:
```
const generator = new JavaGenerator({
  processorOptions: {
    interpreter: {
      allOf: (schema, model, interpreter, interpreterOptions) => {
        // some custom logic for interpreting "allOf"
      }
    }
  }
});
```

**Related issue(s)**
https://github.com/asyncapi/modelina/issues/916

2022-12-29 15:27 UTC, artur-ciocanu commented
@jonaslagoni this one is back 😄 . Could you please take a look. Thank you.

2022-12-29 19:14 UTC, jonaslagoni requested changes
@artur-ciocanu nice!

We do need some extra changes though, cause without them, the users won't the feature is there! So we need to make the documentation reflect the use-case and then provide an example where you show how it can be done 🙂

2023-01-02 15:40 UTC, 200Puls commented
This is really super useful. 
We were debating on creating something similar for our usecase (turning additionalProperties to false)

2023-01-04 13:00 UTC, artur-ciocanu commented
> @artur-ciocanu nice!
> 
> We do need some extra changes though, cause without them, the users won't the feature is there! So we need to make the documentation reflect the use-case and then provide an example where you show how it can be done 🙂

@jonaslagoni I am still new to this, so could you please let me know where should I add the examples and the docs?

2023-01-05 02:10 UTC, jonaslagoni commented
@artur-ciocanu you can find out how to create new examples here: https://github.com/asyncapi/modelina/blob/next/docs/contributing.md#adding-examples

For the docs it's slightly trickier, I think we need a section here: https://github.com/asyncapi/modelina/blob/next/docs/advanced.md

It should explain the use-case of when you would want to use this feature of overwriting the interpreters as well as a link to the example you created 🙂

2023-01-23 13:22 UTC, artur-ciocanu commented
@jonaslagoni I have added an example and a new section to docs. Let me know if it is looking good.

2023-01-23 14:26 UTC, jonaslagoni reviewed
Something I have been wondering, cant recall if we already discussed this, but if it's really only about turning interpretation on or off for `additionalProperties` and `additionalItems`, we could just add the options `ignoreAdditionalProperties` and `ignoreAdditionalItems` instead of allowing changing the entire interpretation callbacks. 

It would be both easier for the end-user and easier to implement.

But if the use-case is really to allow custom interpretations, that can't be solved by simple boolean options, then I am all aboard this feature. Just need to be for the right reasons 😄

2023-01-23 14:28 UTC, jonaslagoni commented
> Also should I rebase from `master`?

I actually cant recall what needs to change once we merge #674, so lets see 🙂

2023-01-23 16:10 UTC, artur-ciocanu commented
> Something I have been wondering, cant recall if we already discussed this, but if it's really only about turning interpretation on or off for `additionalProperties` and `additionalItems`, we could just add the options `ignoreAdditionalProperties` and `ignoreAdditionalItems` instead of allowing changing the entire interpretation callbacks.
> 
> It would be both easier for the end-user and easier to implement.
> 
> But if the use-case is really to allow custom interpretations, that can't be solved by simple boolean options, then I am all aboard this feature. Just need to be for the right reasons 😄

@jonaslagoni now that you mentioned it, I do think that in some cases we might want to have the full power of interpreter options overwrite. However I would go with simple booleans for addtionalProperties and additionaltems for now and later we can add other options in the form of function overrides.

2023-01-23 16:13 UTC, jonaslagoni commented
Sounds good @artur-ciocanu  👍 Also feel free to re-target the PR to the `master` branch 🙂  I don't think you will encounter any problems, but lets see.

2023-01-23 21:20 UTC, artur-ciocanu commented
Closing this one in favor of https://github.com/asyncapi/modelina/pull/1094.

2023-01-23 21:24 UTC, artur-ciocanu commented
> This is really super useful. We were debating on creating something similar for our usecase (turning additionalProperties to false)

@200Puls I have opened another https://github.com/asyncapi/modelina/pull/1094, please take a look. I have to close this one since `next` branch has been merged to `master`.

2023-01-23 21:24 UTC, closed without merging