fix!: fixes required properties when if/then/else is used
asyncapi/modelina pull request #1149
Opened 2023-03-06 14:17 UTC by kennethaasan

**Description**

- fixes required properties when if/then/else is used by making all properties optional if if/then/else is used

2023-03-08 10:32 UTC, jonaslagoni requested changes
I suggested two alternatives to how to solve this, you missing the recursive part, otherwise the rest looks good 👍

2023-03-15 13:00 UTC, kennethaasan commented on test/interpreter/unit/InterpretIfThenElse.spec.ts
> +describe('Interpretation of oneOf with allOf', () => {
This should be fixed? I can't see this anymore at least :D

2023-03-17 13:07 UTC, kennethaasan commented on src/interpreter/InterpretIfThenElse.ts
> +  schema.required = undefined;
I've been looking at this, and there is no easy way to solve it recursively. It can quickly become a mess. Is that something that can be fixed later?

2023-03-21 11:48 UTC, kennethaasan commented on src/interpreter/InterpretIfThenElse.ts
> +  schema.required = undefined;
Appreciate the help! I actually tried something like that, but the tests in were failing in `InterpretIfThenElse.spec.ts`. But, then I moved the test to `TypeScriptGenerator.spec.ts` like you did, it worked. I fixed the test in `InterpretIfThenElse.spec.ts` by calling the interpreter instead. Let me know what you think.

2023-03-21 17:57 UTC, jonaslagoni requested changes
Just a few comments 👍

2023-03-21 17:57 UTC, jonaslagoni commented on src/interpreter/InterpretIfThenElse.ts
> +import {
Are you sure you want this file, and not just keeping the current code in `interpreter`? 🤔 Or is it to allow better testing?

2023-03-21 17:57 UTC, jonaslagoni commented on src/models/CommonModel.ts
> +  constrictModels: boolean;
We might want to clarify this 🤔 
```suggestion
  /**
    * When models are merged, should merging models constrict the `merging to` model? 
    * If false, `required` keyword would no longer be applied from the `merging from` model.
    */
  constrictModels: boolean;
```

2023-03-22 12:17 UTC, kennethaasan commented on src/interpreter/InterpretIfThenElse.ts
> +export default function InterpretIfThenElse(
true, I can remove if 😄

2023-03-23 11:51 UTC, jonaslagoni approved these changes
LGTM 👍

2023-03-23 11:51 UTC, jonaslagoni commented
/rtm

2023-03-23 11:51 UTC, merged