feat: add python json serialization and deserialization preset
asyncapi/modelina pull request #1181
Opened 2023-03-22 09:14 UTC by prayutsu

**Description**

- Added preset to generate JSON serialization and deserialization methods in python
- Added an example for the same
- Modified documentation for python
- Added test case

**Related issue(s)**

Resolves #1130

2023-03-22 09:16 UTC, prayutsu commented
@jonaslagoni PTAL

2023-03-22 12:17 UTC, jonaslagoni requested changes
Looking good overall, just have a few comments 👍 
- Remember to add your example to the main example readme: https://github.com/asyncapi/modelina/blob/master/examples/README.md

There are a few things that the current implementation does not take into account (I don't think I have explained myself well enough in the issue):

Any properties that are of type `ConstrainedDictionaryModel` with a serializationType = `unwrap`, need to be unwrapped into the enclosing JSON object (this applies to `additionalProperties` in this case). This means that any properties added to the map of additionalProperties (I don't know python syntax that well, so might be some mistakes in the code):
```python
 p1 = Root({
  email: 'test',
  additionalProperties: { email2: 'test2'}
})
print(p1.serializeToJson) 
//Print {email: "test", email2: "test2"} and not { email: 'test', additionalProperties: { email2: 'test2'}}
```

Furthermore, properties names are constrained to whatever the language supports, this means that while the representation is `email` it might have been a completely different name that should be used for serialization ([read more about it here](https://github.com/asyncapi/modelina/blob/master/docs/constraints.md)). instead of the original property name, you need to use the property `unconstrainedPropertyName` when serializing. 

Some JSON libraries support this through annotation, or maybe you need to write more custom code in the serialization method itself. Also, keep in mind that if one of the properties is a ConstrainedReferenceModel it needs to call the same function again on the other class.

It might be that these features are not supported by the native `json` library in python, if they are not, we can still use this as long as we document those restrictions in the documentation 🙂

2023-03-22 14:43 UTC, jonaslagoni commented
@prayutsu no, in your example it would be:
```
{
  unconstrainedProperty1: 'test',
  unconstrainedProperty2: '12323',
  name: {
    first_name: 'John',
    last_name: 'Doe'
  }
}
```

The thought process here is the following:

The class property `additionalProperties` is in this case of type ConstrainedDictionaryModel, with serializationType = unwrap. This means any values within that property should be unwrapped when serializing the class. 

If it was serializationType = normal, it should be serialized as (if the class property `additionalProperties`'s `unconstrainedPropertyName` is `unconstrainedProperty2`):
```
{
  unconstrainedProperty1: 'test',
  unconstrainedProperty2: '12323',
  unconstrainedProperty3: {
    name: {
      first_name: 'John',
      last_name: 'Doe'
    }
  }
}
```
In any way, properties defined within a dictionary will always be as is 🙂 

It might also be that `email` should be rendered as `email`, but regardless that value still be accessible through `unconstrainedPropertyName`.

Dont hesitate to ask further clarifications, it's not an easy topic 😅

2023-03-22 17:45 UTC, prayutsu commented
> @prayutsu no, in your example it would be:
> 
> ```
> {
>   unconstrainedProperty1: 'test',
>   unconstrainedProperty2: '12323',
>   name: {
>     first_name: 'John',
>     last_name: 'Doe'
>   }
> }
> ```
> 
> The thought process here is the following:
> 
> The class property `additionalProperties` is in this case of type ConstrainedDictionaryModel, with serializationType = unwrap. This means any values within that property should be unwrapped when serializing the class.
> 
> If it was serializationType = normal, it should be serialized as (if the class property `additionalProperties`'s `unconstrainedPropertyName` is `unconstrainedProperty2`):
> 
> ```
> {
>   unconstrainedProperty1: 'test',
>   unconstrainedProperty2: '12323',
>   unconstrainedProperty3: {
>     name: {
>       first_name: 'John',
>       last_name: 'Doe'
>     }
>   }
> }
> ```
> 
> In any way, properties defined within a dictionary will always be as is 🙂
> 
> It might also be that `email` should be rendered as `email`, but regardless that value still be accessible through `unconstrainedPropertyName`.
> 
> Dont hesitate to ask further clarifications, it's not an easy topic 😅

I couldn't find any reference to implement this with `json` library (or any other library).

2023-03-23 01:59 UTC, leigh-johnson commented
Hey @prayutsu, thank you for all the hard work on this PR. :bowing_woman: It's awesome to see more Pythonistas contributing to Modelina!

I tried out this PR against some of my real-world AsyncAPI schemas since those always help me grok what's going on inside Modelina's generators. I noticed that enum serialization raises an AttributeError:

```
o = mappingproxy({'_generate_next_value_': <function Enum._generate_next_value_ at 0x7f1358ab9090>, '__module__': 'printna...tup'>, 'SHUTDOWN': <OctoPrintServerStatus.SHUTDOWN: 'Shutdown'>, '__new__': <function Enum.__new__ at 0x7f1358ab9000>})

>   return json.dumps(self.__dict__, default=lambda o: o.__dict__, indent=2)
E   AttributeError: 'mappingproxy' object has no attribute '__dict__'
```

Here's the relevant schema object ([full schema here](https://github.com/bitsy-ai/printnanny-asyncapi-schema/blob/main/2.4.0/printnanny-octoprint.yml#L116), if you'd like more context)
```
OctoPrintServerStatusChanged:
  name: OctoPrintServerStatusChanged
  summary: "OctoPrint server status changed"
  payload:
    x-parser-schema-id: OctoPrintServerStatusChanged
    additionalProperties: false
    properties:
      status:
        $ref: "#/components/schemas/OctoPrintServerStatus"
    required:
      - status
```

Generated model code:
```python
from enum import Enum
class OctoPrintServerStatus(Enum): 
  STARTUP = "Startup"
  SHUTDOWN = "Shutdown"
```

I'll follow up with some ideas on how to handle this in my next post.

2023-03-23 02:32 UTC, leigh-johnson commented
IMO, the most Pythonic way to handle this is to extend `json.JSONEncder`

1. For the pydanic preset, pydantic implements a `model.json(...)` method

2. Without the pydanic preset, `json.dumps()` accepts a `cls=<subclass of json.JSONEncder>` keyword-argument. 

Here's a super-exhaustive example of #2, with my approach for coercing various numpy types, enums to string, and datetime to an ISO 8601 strings in another Python project. 
```
import json
from enum import Enum
import numpy as np
import datetime
from io import BytesIO
import base64
import PIL

class NumpyEncoder(json.JSONEncoder):
    def default(self, obj):
        if isinstance(obj, np.integer):
            return int(obj)
        elif isinstance(obj, np.floating):
            return float(obj)
        elif isinstance(obj, np.ndarray):
            return obj.tolist()
        elif isinstance(obj, (datetime.date, datetime.datetime)):
            return obj.isoformat()
        elif isinstance(obj, BytesIO):
            obj.seek(0)
            obj = obj.read()
            return base64.b64encode(obj).decode()
        elif isinstance(obj, bytes):
            return obj.decode()
        elif isinstance(obj, PIL.Image.Image):
            buffered = BytesIO()
            obj.save(buffered, format="JPEG")
            return base64.b64encode(buffered.getvalue()).decode()
        elif isinstance(obj, Enum):
            return obj.value
        return json.JSONEncoder.default(self, obj)
```

How about something like this for Modelina?
```
import json
from enum import Enum

class ModelinaEncoder(json.JSONEncoder):
    """
        A JSON encoder intended for use with Modelina-generated models
    """
    def default(self, obj):
        if hasattr(obj,'toDict'):
            return obj.toDict()
        elif isinstance(obj, Enum):
            return obj.value
        return json.JSONEncoder.default(self, obj)

class ModelinaBaseClass:
    """
        A base class to be used in src/generator/python/renderers/ClassRenderer.ts
    """

    def toDict(self):
        return dict(<render field=self.field here>)
    
    def toJson(self):
        return json.dumps(self.toDict(), cls=ModelinaEncoder)
```

2023-03-23 10:29 UTC, prayutsu commented
@leigh-johnson @jonaslagoni Just an FYI, I'll get back to this PR after a few days as I am currently focusing on writing a GSoC proposal.

2023-04-03 20:45 UTC, jonaslagoni commented
@prayutsu any update? 🙂 Do you have any questions?

2023-04-10 08:19 UTC, prayutsu commented
@jonaslagoni will update docs to include the limitation

2023-04-20 04:54 UTC, jonaslagoni requested changes
Sorry for the long wait @prayutsu! 

Didn't catch that it was done, remember to use the `re-request review` button that lets me know I need to review it again 🙂  
![image](https://user-images.githubusercontent.com/13396189/233261737-b70c577f-57fe-48a8-92d4-26700482a487.png)

Only have one comment other than that it's ready to be merged 👍

2023-04-20 04:54 UTC, jonaslagoni commented on examples/python-generate-json-serializer-and-deserializer/index.spec.ts
> +describe('Should be able to render TEMPLATE', () => {
```suggestion
describe('Should be able to render JSON serialization and deserialization functions', () => {
```

2023-04-20 07:57 UTC, prayutsu commented
@jonaslagoni Made the changes. Will keep in mind to re-request a review in the future.

2023-04-20 07:58 UTC, jonaslagoni requested changes
You will need to update the snapshots as well 🙂 `npm run test:examples:update`

2023-04-20 20:55 UTC, jonaslagoni approved these changes
LGTM 👍

2023-04-20 20:56 UTC, jonaslagoni commented
/rtm

2023-04-20 21:05 UTC, merged

2023-04-20 21:50 UTC, jonaslagoni commented
@all-contributors please add @prayutsu for code, example, test, docs