feat: php generator from official template
asyncapi/modelina pull request #1196
Opened 2023-03-27 22:00 UTC by Ferror

The first step of scoped PHP generator. Creating empty generator from template.

https://github.com/asyncapi/modelina/issues/1195

2023-03-29 02:26 UTC, jonaslagoni requested changes
You have some linter errors @Ferror.

Do you want the PHP generator released in its current form or is it still a bit WIP? 

Remember, once merged into master and part of v1, you must uphold https://github.com/asyncapi/modelina#versioning-and-maintenance 🙂 

If you want to continue the development a bit more, we could create a temporary branch for you to work on for a bit of time. It will mean it won't be released, but then you make any change you wish while it's work in progress.

2023-03-31 22:46 UTC, jonaslagoni commented
> @jonaslagoni I want to iterate over the generator, but I don't want to keep it in one PR. However, you want to make it right. Long-living PRs do not suite me well

I think we should keep this in a `php_generator` branch in Modelinas side, and progress there 🙂 That means you can make any type of change without having to worry about breaking anything.

And then we can slowly progress the generator until you feel like it's ready to be released 🙂 

How does that sound?

2023-04-01 15:56 UTC, Ferror commented
>
> How does that sound?

Awsome. Let's go!

2023-04-01 17:11 UTC, jonaslagoni approved these changes

2023-04-01 17:11 UTC, merged