FEAT: Added TypescriptOption for ModuleSystem & UI for Typescript generation using ModuleSystem
asyncapi/modelina pull request #1223
Opened 2023-04-06 15:31 UTC by ishaan812

**Description**
- Added option for generation of TypeScript using different module systems
- Added UI to support this operation in Playground

![image](https://user-images.githubusercontent.com/70190533/230427070-bbb73a4e-6362-4527-8b77-6b3f5da51624.png)

**Related issue(s)**
Resolves #1173

2023-04-06 22:35 UTC, jonaslagoni requested changes
Just one change 😄

2023-04-06 22:35 UTC, jonaslagoni commented on modelina-website/src/components/playground/options/TypeScriptGeneratorOptions.tsx
> +      console.log(moduleSystem)
This needs to be removed 🙂

2023-04-08 05:01 UTC, ishaan812 commented
Yup should be good now

2023-04-08 09:33 UTC, ishaan812 reviewed
made the change

2023-04-08 12:38 UTC, jonaslagoni approved these changes
LGTM 👍

2023-04-08 12:38 UTC, jonaslagoni commented
/rtm

2023-04-08 12:48 UTC, merged

2023-04-20 05:05 UTC, jonaslagoni commented
@all-contributors please add @ishaan812 for code