feat: add error component in playground
asyncapi/modelina pull request #1232
Opened 2023-04-12 09:41 UTC by Samridhi-98

**Description**

This PR adds a feat to the modelina website that shows error message on the request failure to generate model.

_**Task Done**_

- [x]  Created `CustomError` component.

- [x] Added new state for error handling in the Playground component. 

_**Todo**_

- [ ] Needs to add logic for hardcode statusCode and error message in the error component.

 
**Related issue(s)**

- Fixes #1167 

**Screenshot**

![image](https://user-images.githubusercontent.com/54466041/231417578-c85d112c-e6fa-4901-a3da-bd9c68f1987e.png)

2023-04-12 12:52 UTC, jonaslagoni commented
> [ ] Needs to add logic for hardcode statusCode and error message in the error component.

@Samridhi-98 wanna merge this PR and continue to slowly improve it? Or do you want to include it in this PR?

2023-04-12 12:53 UTC, jonaslagoni approved these changes
LGTM 👍

2023-04-12 13:42 UTC, Samridhi-98 commented
> > [ ] Needs to add logic for hardcode statusCode and error message in the error component.
> 
> @Samridhi-98 wanna merge this PR and continue to slowly improve it? Or do you want to include it in this PR?

No no, still working on it 😅

2023-04-20 04:50 UTC, jonaslagoni commented
Hey @Samridhi-98, is anything blocking you to move forward, or something you wish to discuss?

2023-04-20 08:27 UTC, Samridhi-98 commented
Hi @jonaslagoni, please review and let me know if any change is needed 🙂

2023-04-20 13:10 UTC, jonaslagoni requested changes
Looks good in general 👍 

Seems like It does not throw an error when incorrect AsyncAPI documents are provided, for example, try this:
```json
{
  "asyncapi": "2.6.0",
  "info": {
    "title": "Kraken Websockets API",
    "version": "1.8.0",
    "description": "test"
  },
  "channels": {
    "/": {
      "publish": {
        "description": "Send messages to the API",
        "operationId": "processReceivedMessage",
        "message": {
            "$ref": "#/components/messages/noneexisting"
        }
      }
    }
  }
}
```


The only remarks to the design are, It's hard to see the error message, dark on dark, it would be great to have some more contrast. Would that be possible? 🤔 

![image](https://user-images.githubusercontent.com/13396189/233372496-aeceff25-83a8-4b8c-ad27-7ea5c33db0e6.png)

2023-04-20 15:28 UTC, Samridhi-98 commented on modelina-website/src/pages/api/generate.ts
> +    'dart': getDartModels,
Sure, I'll do the suggested changes. 🙂

2023-04-21 09:18 UTC, jonaslagoni commented
@Samridhi-98 still think the bottom text should be a different color, I can barely see it my self 😅 Maybe white?
 
![image](https://user-images.githubusercontent.com/13396189/233597838-1e11c6e0-4fdd-441e-8a50-59ffbb52ad27.png)

Did you test with this input that should give an error? Still does not give anything 🤔 
```
{
  "asyncapi": "2.6.0",
  "info": {
    "title": "Kraken Websockets API",
    "version": "1.8.0",
    "description": "test"
  },
  "channels": {
    "/": {
      "publish": {
        "description": "Send messages to the API",
        "operationId": "processReceivedMessage",
        "message": {
            "$ref": "#/components/messages/noneexisting"
        }
      }
    }
  }
}
```

2023-04-24 04:24 UTC, Samridhi-98 commented
> @Samridhi-98 still think the bottom text should be a different color, I can barely see it my self 😅 Maybe white?
> 
> ![image](https://user-images.githubusercontent.com/13396189/233597838-1e11c6e0-4fdd-441e-8a50-59ffbb52ad27.png)
> 
> Did you test with this input that should give an error? Still does not give anything 🤔
> 
> ```
> {
>   "asyncapi": "2.6.0",
>   "info": {
>     "title": "Kraken Websockets API",
>     "version": "1.8.0",
>     "description": "test"
>   },
>   "channels": {
>     "/": {
>       "publish": {
>         "description": "Send messages to the API",
>         "operationId": "processReceivedMessage",
>         "message": {
>             "$ref": "#/components/messages/noneexisting"
>         }
>       }
>     }
>   }
> }
> ```

Oh! I changed it to red just like image and heading components maybe it overrides the CSS.

2023-04-24 04:44 UTC, Samridhi-98 commented
Hi @jonaslagoni, I have resolved the color and error message issue by rectifying the override of the paragraph component's text color. I have fixed text color to red,  Please suggest if it would be fine or prefer it to be changed to white.

2023-04-24 09:59 UTC, jonaslagoni approved these changes
LGTM 👍

2023-04-24 09:59 UTC, merged