remove LouisXhaferi from contributor lists
asyncapi/modelina pull request #1275
Opened 2023-05-06 19:31 UTC by LouisXhaferi

**Description**
As I've practically not put any all that much time into modelina, since I first joined as a contributor, and won't be able to do so in the future, I'd step down as contributor/codeowner etc. 

I'll probably do the same for the TSC, as my focus shifted away from cloud and messaging related stuff.

2023-05-06 19:32 UTC, LouisXhaferi commented on README.md
pain, random reformatting by IntelliJ all over the place.

2023-05-06 21:18 UTC, jonaslagoni requested changes
Sad to see you go, but best of luck in your new adventure! You are free to come back any time 👍 

Only change the code owners file, no need to remove all traces of you contributing to the repo 😄

2023-05-06 21:18 UTC, jonaslagoni commented on .all-contributorsrc
> -        "maintenance"
Just remove maintenance 🙂 You still contributed with the rest 🙂

2023-05-07 06:52 UTC, LouisXhaferi commented
> Sad to see you go, but best of luck in your new adventure! You are free to come back any time 👍
> 
> Only change the code owners file, no need to remove all traces of you contributing to the repo 😄

Thank you!

2023-05-07 09:45 UTC, jonaslagoni approved these changes

2023-05-07 09:45 UTC, merged