feat: add rust runtime tests
asyncapi/modelina pull request #1331
Opened 2023-05-25 20:59 UTC by Shurtu-gal

**Description**
Add Runtime testing for rust

**Related issue(s)**
Fixes #1295

2023-05-25 21:18 UTC, jonaslagoni requested changes
It's probably a bug with th generated rust code 🙂 We had it for Java as well 🙂 See https://github.com/asyncapi/modelina/issues/1294. 

[The test input](https://github.com/asyncapi/modelina/blob/master/test/runtime/generic-input.json) contains all the different variants of models. And it might be the generator does not correctly handle them 100%. So I would create a bug and then ignore the errors. We can merge this PR regardless 🙂 

Remember to add the GitHub workflow as well 🙂

2023-05-25 21:32 UTC, Shurtu-gal commented
Sure I will do it.

2023-05-25 22:50 UTC, jonaslagoni commented
LGTM 🔥 👍

@leigh-johnson wanna have a look?

2023-05-31 10:44 UTC, Shurtu-gal commented on test/runtime/runtime-rust.spec.ts
> +jest.setTimeout(100000);
Done 👍🏻.
The errors are due to error in generator (PartialEQ especially) right now.

2023-06-02 13:24 UTC, Shurtu-gal commented
@jonaslagoni the required changes are done 👍🏻.
The errors are due to error in generator (PartialEQ especially) right now.

2023-06-02 13:27 UTC, jonaslagoni commented
> The errors are due to error in generator (PartialEQ especially) right now. 

And that's perfect 😄 Thats exactly why we do these tests. Do you mind creating an issue for the bug (unless there already is an issue for it)?

2023-06-02 13:40 UTC, Shurtu-gal commented
@jonaslagoni Did it. Here's the link https://github.com/asyncapi/modelina/issues/1361

2023-06-02 13:41 UTC, jonaslagoni approved these changes
LGTM 👍

2023-06-02 13:42 UTC, merged

2023-06-02 13:43 UTC, jonaslagoni commented
Awesome work @Shurtu-gal, feel free to expand on the Rust runtime testing if you wish, this is something that really catches a lot of good stuff as you have already seen 🔥

2023-06-02 13:44 UTC, jonaslagoni commented
@all-contributors please add @Shurtu-gal for test and infra