Fix warning created by not respecting nullable parameter.
asyncapi/modelina pull request #1356
Opened 2023-05-31 19:09 UTC by JFCote

This is my first PR for this project. I must say that I'm not a Typescript pro and I don't have a working setup on my desktop.
I hope one of the maintainer can help me finish and complete this PR! I will help as much as I can to have it merged and released as soon as possible :)

**Description**

- Added via a `handleNullable` param to the C# generator that is defaulted to "false" to not create breaking changes
- Add code to prevent warning when compiling the C# classes when the project is "nullable" in C# .NET

For autoImplementedProperties, it will look like that when a property is not required:

`public string Id { get; set; } = null!;` instead of `public string Id { get; set; }`

Without autoImplementedProperties, it will look like this:

`private string _id = null!;` instead of `private string _id;`

**Related issue(s)**

No issues were created for this, I went strictly to code because it was very simple to implement.

2023-06-02 13:36 UTC, jonaslagoni requested changes
Thanks for taking the time to fix this 🙏 

Do you want this to be part of v2 instead (just create the change on the `next` branch)? then you don't have to introduce the option `handleNullable` if this should always be the preferred output 🙂 

If not, then you are still missing some tests that show it works with the new option 😄

2023-06-02 13:36 UTC, jonaslagoni commented on src/generators/csharp/renderers/ClassRenderer.ts
> +      nullablePropertyEnding = '= null!';
I would change this to
```suggestion
      nullablePropertyEnding = ' = null!';
```

2023-06-02 13:36 UTC, jonaslagoni commented on src/generators/csharp/renderers/ClassRenderer.ts
> +      )} { ${getter} ${setter} } ${nullablePropertyEnding}${semiColon}`;
I would change this to
```suggestion
      return `public ${property.property.type} ${pascalCase(
        property.propertyName
      )} { ${getter} ${setter} }${nullablePropertyEnding};`;
```

2023-06-02 13:36 UTC, jonaslagoni commented on src/generators/csharp/renderers/ClassRenderer.ts
> +    return `private ${property.property.type} ${property.propertyName} ${nullablePropertyEnding};`;
And then you can do this 😄 
```suggestion
    return `private ${property.property.type} ${property.propertyName}${nullablePropertyEnding};`;
```

2023-06-02 14:09 UTC, JFCote commented
> Do you want this to be part of v2 instead (just create the change on the `next` branch)? then you don't have to introduce the option `handleNullable` if this should always be the preferred output 🙂

Well it's good that it is an option because in C# it is an option in each project. In .NET 6.0 it default to nullable = true but anyone can put it to false. So I think it's good that it is an option for the users :)

As for the tests, I completely forgot this part, I'm not very used to typescript. I will try to add them. Thanks!

2023-06-02 14:25 UTC, JFCote commented on src/generators/csharp/renderers/ClassRenderer.ts
> +      nullablePropertyEnding = '= null!';
Fixed in latest commit

2023-06-02 14:25 UTC, JFCote commented on src/generators/csharp/renderers/ClassRenderer.ts
> +      )} { ${getter} ${setter} } ${nullablePropertyEnding}${semiColon}`;
fixed in latest commit

2023-06-02 14:25 UTC, JFCote commented on src/generators/csharp/renderers/ClassRenderer.ts
> +    return `private ${property.property.type} ${property.propertyName} ${nullablePropertyEnding};`;
fixed in latest commit

2023-06-02 14:28 UTC, jonaslagoni commented
Forgot to mention we actually adding features pretty well documented here: https://github.com/asyncapi/modelina/blob/master/docs/contributing.md#new-features 😄 

Remember to also add the following:
- Please add a section in the C# readme about this feature: https://github.com/asyncapi/modelina/blob/master/docs/languages/Csharp.md
- Please add an example show-casing this new feature: https://github.com/asyncapi/modelina/blob/master/docs/contributing.md#adding-examples

2023-06-02 15:02 UTC, JFCote commented
@jonaslagoni I just added everything that was asked for (I think!). Let me know if something is missing and I will add it!

2023-06-02 15:27 UTC, jonaslagoni reviewed
Awesome, nicely done for your first contribution 🔥 

Interested in helping out with other stuff? 😄 

Giving @ron-debajyoti a day to respond and then we merge 👍

2023-06-02 15:33 UTC, JFCote commented
@jonaslagoni My team and I will start using asyncapi seriously in a very big project so we will probably have other contributions coming your way. It might not be all in modelina because we are also creating custom template for asyncapi generator so it might me all over the place in the asyncapi community! :)
Thanks for the very good support and ownership of the project!

2023-06-05 11:04 UTC, jonaslagoni approved these changes

2023-06-05 11:13 UTC, merged

2023-06-05 11:51 UTC, jonaslagoni commented
@JFCote ahh, missed that one 😅 

No worries, I'll fix it 🙂