Added runtime testing for Go models  #1333
asyncapi/modelina pull request #1484
Opened 2023-08-18 18:57 UTC by Devansh-Bhatt

**Description**

- Added Runtime Testing for Go models
- Resolved the 8 tasks as listed in #1333 

**Related issue(s)**
Resolves #1333

2023-08-19 16:45 UTC, jonaslagoni requested changes
Looks great @Devansh-Bhatt!

Just got those two comments, and then please use `test:` as the PR title 🙂

2023-08-19 16:45 UTC, jonaslagoni commented on test/runtime/runtime-go/Test_Go/Test_Address.go
> +		AdditionalProperties: nil,
@Devansh-Bhatt if you look at one of the other runtime test, do you mind using the same values as in there? 🙂

2023-08-19 16:45 UTC, jonaslagoni commented on test/runtime/runtime-go/Test_Go/Test_Address.go
> +func TestShouldbeAbleToSerializeModel(t *testing.T) {
We still need to compare the actual serialized value with something we expect, you can grab the one in the other runtime test 🙂

2023-08-22 09:55 UTC, jonaslagoni commented on test/runtime/runtime-go/Test_Go/Test_Address.go
> +func TestShouldbeAbleToSerializeModel(t *testing.T) {
Yep, thats about it 👍

2023-08-27 14:23 UTC, Devansh-Bhatt commented
@jonaslagoni Is there any issue with the commit / changes that i made. I quite don't seem to understand what's the issue here 😕

2023-08-28 00:05 UTC, jonaslagoni approved these changes
LGTM 👍

2023-08-28 00:06 UTC, merged

2023-08-28 00:06 UTC, jonaslagoni commented
@all-contributors please add @Devansh-Bhatt  for test, infra