Add csharp support for DateTime, TimeSpan, Guid #1607
asyncapi/modelina pull request #1612
Opened 2023-11-16 11:45 UTC by jano-petras

**Description**

Extending supported string formats for C#:

- format: 'date-time' will be rendered as DateTime in C#
- format: 'time' will be rendered as TimeStamp in C#
- format: 'uuid' will be rendered as Guid in C#

Added relevant tests and extended existing examples where relevant

**Related issue(s)**
Resolves #1607

2023-11-16 18:47 UTC, jonaslagoni requested changes
Nice @jano-petras!

Just need to run `npm run lint:fix` and add a small section in the migration docs about this breaking change for the C# models: https://github.com/asyncapi/modelina/blob/next/docs/migrations/version-2-to-3.md

Everything else is good 👌

2023-11-17 11:42 UTC, jano-petras commented
Thanks @jonaslagoni, that has been addressed now

2023-11-17 19:23 UTC, jonaslagoni approved these changes
Awesome @jano-petras 🔥

2023-11-17 19:23 UTC, jonaslagoni commented
/rtm

2023-11-17 19:34 UTC, merged

2023-11-17 19:46 UTC, jonaslagoni commented
@all-contributors please add @jano-petras for code, docs, test