Create New Playground Layout
asyncapi/modelina pull request #1628
Opened 2023-11-22 13:37 UTC by devilkiller-ag

**Description**
This is a draft PR for building a new layout of Modelina Playground. The new layout will be similar to the layout of [Async API Studio](https://studio.asyncapi.com/). The first step will be to create a new layout and then I will be working on the logic. I have created a temporary component file `NewPlayground.tsx` to build the new layout. We will replace the old components with the new ones once the layout is ready.

**Related issue(s)**

Resolves #1346

2023-11-24 14:00 UTC, devilkiller-ag commented
Hi @jonaslagoni @codingmickey, I was trying to use [React Split Pane](https://www.npmjs.com/package/react-split-pane) for the section which will show input, output, and the output navigation. But it seems that it haven't been updated since last three years and doesn't support React v18. 

I found this new [react-split-pane implementation by Jeremy Grieshop](https://github.com/JeremyGrieshop/react-split-pane)  which supports React v17 and above. It's also been used in the AsyncAPI Studio. Can I use this instead? The problem is that it isn't available as package so I will have to copy paste whole repo as a component as also done in the studio.

2023-11-27 18:22 UTC, jonaslagoni commented
@devilkiller-ag I would say no, dont use a tool that has no users 🙂 Then its better to have no split pane functionality.

2023-11-27 18:26 UTC, devilkiller-ag commented
Hi @jonaslagoni, I agree with you. For now I have used the code for the split pane from Async API Studio Codebase. But if you want I can try to implement it from scratch for our playground. What's your opinion?

2023-11-28 04:50 UTC, devilkiller-ag commented
> > Hi @jonaslagoni, I agree with you. For now I have used the code for the split pane from Async API Studio Codebase. But if you want I can try to implement it from scratch for our playground. What's your opinion?
> 
> You can select the direction you want to take, there is no requirement here 🙂 We don't have split panel right now anyway, so it can be added later if desired 👌 Then all you need to focus on is the basic layout, making it easier to achieve.

Okay Sure, I will go with the basic layout for now 🙂

2023-11-30 07:14 UTC, devilkiller-ag commented
I have added the mobile responsive layout without split-pane. Now I will add the Editor, Options, and Output UI.

2023-12-04 20:19 UTC, jonaslagoni commented
@devilkiller-ag this is starting to look great!

Only point I have is that it's impossible to see the models + options that are generated. Would it be possible to have the sidebar + input + models + output side by side somehow? 🤔

2023-12-05 04:08 UTC, devilkiller-ag commented
Hi @jonaslagoni, I did exactly that. Strangely, it's not visible on your side. Here is the [recording](https://drive.google.com/file/d/1ed2SO7HfOe6PQuNzCDCxL4zof9YY42J4/view?usp=sharing) of the new UI.

![95c42a87-2a2d-466d-935c-25a4b60436b7](https://github.com/asyncapi/modelina/assets/43639341/d7530c4d-2b90-4350-9d28-d38c2b410fae)

I have also checked the PR [deploy preview](https://deploy-preview-1628--modelina.netlify.app/), and it's working exactly the same as the local deployment. Are you talking about the sidebar, input, output, and models same as shown in the above gif or have I misunderstood something? I'm sorry for the confusion.

2023-12-05 04:11 UTC, jonaslagoni commented
Do you see that when you have the different models visible and what to change the options, the models view disappears?

Thats the part I don't like, i.e. I think the models view should always be visible and maybe right next to the output view 🙂 Similar to what we have in the current modelina playground. We can still have the button in the sidebar to toggle it to be visible and hidden, but it should not be closed just because you want the options 🙂

2023-12-05 04:26 UTC, devilkiller-ag commented
Okay Got it. So you want something like this?
![Screenshot 2023-12-05 095514](https://github.com/asyncapi/modelina/assets/43639341/d031d308-2bf8-4340-8dcc-a9d285c9cdd9)

2023-12-05 05:55 UTC, jonaslagoni commented
Yes 👍

2023-12-08 18:29 UTC, jonaslagoni commented
> Do we need to make the layout mobile responsive? Or Should we ask the user visiting from mobile to visit from desktop? The current layout is not mobile-responsive. Do you have any layout for mobile devices in mind?

I don't think there exists a layout that will work well with a mobile view 🤔 Even in it's current form it's almost impossible to see anything. You could just display all the views on mobile devices like it currently works. I.e. so there is no regression between the current and new version of playground 🤔

2023-12-08 18:37 UTC, devilkiller-ag commented
Did you mean, we should display the old playground layout for mobile viewers? Can't we just display something like this: "Revisit from desktop to use Modelina Playground"?

2023-12-09 02:32 UTC, devilkiller-ag commented
@jonaslagoni The work is complete! Kindly check it out.

2023-12-09 21:55 UTC, jonaslagoni requested changes
Looking great! Got some minor comments 🔥 

Here is what I see and what I base the comments on:
- All the views need to be aligned in height
- The `?` symbol would look better if it blends better with the black background
- I would add more margins to the menu item, as they are too close to the panel to the right.
- The view with the `generator code` and generated models, it's hard to see that  `generator code` can be clicked
- We should make it more easier to see which output model is being selected.
- In the generator options view, for example if you select `kotlin` the panel gets scrollable 🤔 Is there a better way to show long options?

![image](https://github.com/asyncapi/modelina/assets/13396189/3fbcfc34-7972-4ded-9b2d-58ad15dcaf7b)

2023-12-10 18:23 UTC, devilkiller-ag commented
Hi @jonaslagoni,

I have incorporated all the suggestions. Kindly check it out.

2023-12-10 23:36 UTC, jonaslagoni requested changes
You are fast @devilkiller-ag, only got very few remarks. I think this is the final changes needed, checked all the code and it looks great, only got those small points 💪 Cant wait to merge this 🔥  

Think we can change the width of the sidebar menu to 50: 
![image](https://github.com/asyncapi/modelina/assets/13396189/9f33e0e9-158a-4e09-8a09-3b40b6662593)

2023-12-10 23:36 UTC, jonaslagoni commented on modelina-website/src/components/playground/Sidebar.tsx
> +      tooltip: 'Option'
Think we should add a little more explanation here 🤔 
```suggestion
      tooltip: 'Show or hide all the options'
```

Feel free to go with another text if you have one in mind!

2023-12-10 23:36 UTC, jonaslagoni commented on modelina-website/src/components/playground/Sidebar.tsx
> +      tooltip: 'Output'
Think we should add a little more explanation here 🤔 
```suggestion
      tooltip: 'Show or hide the list of output models'
```

Feel free to go with another text if you have one in mind!

2023-12-10 23:36 UTC, jonaslagoni commented on modelina-website/src/components/playground/options/GeneralOptions.tsx
> +        <h3 className="py-2 w-full text-left border-b-[1px] border-gray-700 text-sm">
Setting text-sm and using headers cancel them out 🙂 

```suggestion
        <h3 className="py-2 w-full text-left border-b-[1px] border-gray-700">
```

This is happening in multiple places, included in each language option, I would stick with using appropriate headers and class names 🙂

2023-12-10 23:38 UTC, jonaslagoni commented
Once we merge this I would love to offer you code ownership of the `modelina-website` code, let me know if you want to stick around for longer than a single PR 😉 

Let me know if you have any questions about it 👍

2023-12-11 00:52 UTC, devilkiller-ag commented
Hi @jonaslagoni, I have made all the changes you suggested, additionally, I have changed the Tooltip color and padding to make it visible. Thanks for offering me the code ownership of the `modelina-website`. I would love to be able to contribute forward. I had an issue in mind that I was going to open just after this PR closes: Currently, the website code uses class components, we should update the code base to use functional components and hooks at all places. This will result in cleaner, easier-to-understand components compared to class components. What's your view on this?

2023-12-11 04:11 UTC, jonaslagoni commented
> Hi @jonaslagoni, I have made all the changes you suggested, additionally, I have changed the Tooltip color and padding to make it visible

Perfect 👍 

> I had an issue in mind that I was going to open just after this PR closes: Currently, the website code uses class components, we should update the code base to use functional components and hooks at all places. This will result in cleaner, easier-to-understand components compared to class components. For the Playground, I have updated most of the class components to functional components on which I worked. What's your view on this?

Sounds good, feel free to create an issue for it to track it 🙂

2023-12-11 04:12 UTC, jonaslagoni approved these changes
🔥

2023-12-11 04:13 UTC, jonaslagoni commented
/rtm

2023-12-11 04:13 UTC, merged

2023-12-11 04:16 UTC, jonaslagoni commented
@all-contributors please add @devilkiller-ag for code, design