Adding Scala generator scaffolding
asyncapi/modelina pull request #1665
Opened 2023-12-16 12:20 UTC by artur-ciocanu

**Description**
- Adding Scala generator

**Related issue(s)**
Resolves https://github.com/asyncapi/modelina/issues/1664

2023-12-16 12:20 UTC, artur-ciocanu commented
The PR is WIP ...

2023-12-16 20:18 UTC, jonaslagoni commented
Let me know if you need anything from me @artur-ciocanu 🤙 Looking forward to having this!

2023-12-18 22:56 UTC, jonaslagoni commented
@artur-ciocanu you can ignore sonar duplication warning

2023-12-18 23:01 UTC, jonaslagoni requested changes
Only thing left to do as I see is adding simple generate example: https://github.com/asyncapi/modelina/tree/master/examples/generate-java-models

There is a template you can copy and change 🙂

2023-12-18 23:01 UTC, jonaslagoni commented on package.json
> +    "format-now": "prettier --config .prettierrc test/generators/scala/ScalaGenerator.spec.ts --write"
```suggestion
```

2023-12-23 13:07 UTC, artur-ciocanu commented on package.json
> +    "format-now": "prettier --config .prettierrc test/generators/scala/ScalaGenerator.spec.ts --write"
Good catch 😄

2023-12-23 13:09 UTC, artur-ciocanu commented
@jonaslagoni it seems that I have covered everything that is required for Scala code gen. Once this PR is out, I'll add some JSON serialization preset and Jakarta validation preset.

Let me know your thought and if there is anything else required.

Thank you!

2023-12-23 13:20 UTC, jonaslagoni approved these changes
Awesome @artur-ciocanu, thanks for taking the time to provide it 🤙 Got a couple of small things that needs to be added, but Ill create issues after, not required to merge 😄

Also, do you want to become the codeowner of the scala generator, or are you only looking to donate it? ✌️

2023-12-23 13:20 UTC, jonaslagoni commented
/rtm

2023-12-23 13:21 UTC, merged

2023-12-23 13:33 UTC, jonaslagoni commented
@all-contributors please add @artur-ciocanu for code, example, docs, test

2023-12-23 13:46 UTC, artur-ciocanu commented
> Awesome @artur-ciocanu, thanks for taking the time to provide it 🤙 Got a couple of small things that needs to be added, but Ill create issues after, not required to merge 😄
> 
> Also, do you want to become the codeowner of the scala generator, or are you only looking to donate it? ✌️

@jonaslagoni I can be a code owner, I would like to get rid of my "internal" fork and just maintain the official Modelina version.

Thanks for merging it!

2023-12-23 14:00 UTC, jonaslagoni commented
> @jonaslagoni I can be a code owner, I would like to get rid of my \"internal\" fork and just maintain the official Modelina version.

Awesome, thanks for doing it! Added a PR to add you 🤙 https://github.com/asyncapi/modelina/pull/1686