docs: adds C++ constraint docs
asyncapi/modelina pull request #1696
Opened 2023-12-26 16:49 UTC by ankur0904

## Description
Adds the missing `C++` constraint docs. 

## Related Issue
Fix #1671

2023-12-27 05:46 UTC, jonaslagoni commented on docs/constraints/Cplusplus.md
> +|NAMING_FORMATTER|Must be formatted equally|Model name is formatted using pascal case|
```suggestion
|NAMING_FORMATTER|Must be formatted equally|Property naming is formatted using pascal case|
```

2023-12-27 05:46 UTC, jonaslagoni commented on docs/constraints/Cplusplus.md
> +|NAMING_FORMATTER|Must be formatted equally|Model name is formatted using pascal case|
```suggestion
|NAMING_FORMATTER|Must be formatted equally|Enum key is formatted using pascal case|
```

2023-12-27 05:50 UTC, jonaslagoni requested changes
Just got one comment 💪

2023-12-27 05:50 UTC, jonaslagoni commented on docs/constraints/Cplusplus.md
> +|NAMING_FORMATTER|Must be formatted equally|Model name is formatted using pascal case|
The model namings use `toSnakeCase` function not pascal case, please double check that the implementation and docs (for all the constraints) are matching: https://github.com/asyncapi/modelina/blob/cbf55179f37adaa9b67564b2fc022615d7c66095/src/generators/cplusplus/constrainer/EnumConstrainer.ts#L42C35-L42C46

2023-12-27 18:37 UTC, ankur0904 commented
@jonaslagoni  Made some changes. Notice that only `_` is excluded in the code, so I removed the `$` sign as well.
https://github.com/asyncapi/modelina/blob/cbf55179f37adaa9b67564b2fc022615d7c66095/src/generators/cplusplus/constrainer/EnumConstrainer.ts#L33

2023-12-28 13:33 UTC, jonaslagoni approved these changes
Cool, thanks @ankur0904 🤙

2023-12-28 13:33 UTC, merged

2023-12-28 17:14 UTC, ankur0904 commented
hey, @jonaslagoni can I become part of a contributor for doc, maintenance?

2023-12-30 00:45 UTC, jonaslagoni commented
@ankur0904 docs for sure, however maintenance is for those who are code owners 😄

If you want to become a codeowner read more here: https://github.com/asyncapi/modelina/issues/1148

2023-12-30 00:45 UTC, jonaslagoni commented
@all-contributors please add @ankur0904 for docs

2023-12-31 17:12 UTC, ankur0904 commented
Thanks @jonaslagoni