feat: added support for OpenAPI version 3.1.0
asyncapi/modelina pull request #1778
Opened 2024-02-04 09:30 UTC by Athul0491

## Description
Adds support for OpenAPI version 3.1

## Related Issue
Add OpenAPI 3.1 support #1749
## Checklist
- [x] The code follows the project's coding standards and is properly linted (`npm run lint`).
- [ ] Tests have been added or updated to cover the changes.
- [ ] Documentation has been updated to reflect the changes.
- [x] All tests pass successfully locally.(`npm run test`).

2024-02-06 13:27 UTC, jonaslagoni requested changes
@Athul0491 please add an example and adapt the docs to reflect the new supported input✌️

Let me know if you need pointers

2024-02-06 22:44 UTC, Athul0491 commented
@jonaslagoni Will an example similar to [openapi-from-object](https://github.com/asyncapi/modelina/tree/master/examples/openapi-from-object) be sufficient?

2024-02-07 05:59 UTC, jonaslagoni commented
@Athul0491 yep exactly 👍 also make sure you adapt test file for the input processor

2024-02-13 12:20 UTC, jonaslagoni commented
@Athul0491 have you had time to take another look at it? :v:

2024-02-19 10:00 UTC, jonaslagoni commented on examples/openapi-v3_1-from-object/index.spec.ts
> +import { generate } from './index';
Please commit the snapshots as well 🙂

2024-02-22 11:43 UTC, jonaslagoni requested changes
I am pretty sure the package-lock changes are stopping the tests for working. I have seen that error before 🤔 

Did you make the `npm i` with node 18 or 16? 🤔 

Everything else looks fine to me tbh 👍

2024-02-22 16:16 UTC, Athul0491 commented
I ran `npm i` with node 18.18.2

2024-02-23 10:17 UTC, jonaslagoni commented
@Athul0491 do you mind grabbing the package-lock from master and copy it over, and do a simple `npm i` again? 🤔

2024-02-27 08:31 UTC, jonaslagoni approved these changes
Perfect 👌

2024-02-27 08:31 UTC, jonaslagoni commented
/rtm

2024-02-27 08:32 UTC, merged

2024-02-27 08:32 UTC, jonaslagoni commented
@all-contributors please add @Athul0491 for code, example, docs, test