Export and import interfaces as types when using named imports and ESM Module Syntax
asyncapi/modelina pull request #1800
Opened 2024-02-13 13:56 UTC by moritzkalwa

## Description
When using modelType 'interface', exportType 'named' and moduleSystem 'ESM' export and import interfaces as types to support verbatimModuleSyntax.

## Related Issue
#1793 

## Checklist
- [ ] The code follows the project's coding standards and is properly linted (`npm run lint`).
- [ ] Tests have been added or updated to cover the changes.
- [ ] Documentation has been updated to reflect the changes.
- [ ] All tests pass successfully locally.(`npm run test`).

## Additional Notes
We might want to document the fact that one needs to use named exports when using interfaces and verbatimModuleSyntax. Im not sure where this documentation should go though, please point me in the right direction here :D

2024-02-14 13:41 UTC, jonaslagoni requested changes

2024-02-14 13:41 UTC, jonaslagoni commented on test/generators/typescript/TypeScriptGenerator.spec.ts
> +    expect(models).toHaveLength(2);
If you want to test the generated complete models, please create a test just for this 🙂 As it's two different renderings and what they test :v:

2024-02-14 22:28 UTC, moritzkalwa commented
@jonaslagoni Do you think it would be okay to change [this example](https://github.com/asyncapi/modelina/blob/master/examples/typescript-interface/index.ts) to use exportType 'named' and moduleSystem 'ESM' to show these changes?

2024-02-15 08:06 UTC, jonaslagoni commented
I would duplicate it and create one that shows it with those settings 🙂 You can follow this: https://github.com/asyncapi/modelina/blob/master/docs/contributing.md#adding-examples

2024-02-17 15:27 UTC, jonaslagoni requested changes
Just a small change

2024-02-17 15:27 UTC, jonaslagoni commented on examples/typescript-interfaces-as-types/README.md
> +# TypeScript interface
```suggestion
# TypeScript interface as types
```

2024-02-17 15:28 UTC, jonaslagoni approved these changes

2024-02-17 15:28 UTC, jonaslagoni commented
/rtm

2024-02-17 17:36 UTC, merged

2024-02-21 08:47 UTC, mikaellanger commented
This makes enum values unusable when using enumType 'enum' since it also exports enums as types not just interfaces, leading to
`MyEnum' cannot be used as a value because it was exported using 'export type'.`
when doing e.g. MyEnum.AnEnumValue

2024-02-21 11:14 UTC, jonaslagoni commented
Thanks for raising the issue @mikaellanger

Reverting commit in master.

Taking a second look, this should be targeting `next` because of the breaking changes in the dependency manager: https://github.com/asyncapi/modelina/pull/1800/files#diff-95c504c5267dbd4e90a8ee687814eabaf191637b94093293b968648836d91d39R21