fix: switch to Object.Equals for C# Equals override
asyncapi/modelina pull request #1865
Opened 2024-03-06 20:19 UTC by Louis-PhilippeGentile

## Description

The changes included in this pull request modify the common preset for the C# generator. It removes the use of `==` in the `Equals` override and replaces it with `Object.Equals`.

- Replaces `==` with `Object.Equals()` when overriding `Equals` for C# model generation
- Updates test related to the `Equals` override
- Adds a note regarding the limitations of the `Equals` override

## Related Issue

Fixes #1850 

## Checklist
- [ ] The code follows the project's coding standards and is properly linted (`npm run lint`).
- [ ] Tests have been added or updated to cover the changes.
- [ ] Documentation has been updated to reflect the changes.
- [ ] All tests pass successfully locally.(`npm run test`).

## Additional Notes

2024-03-07 10:32 UTC, jonaslagoni commented
cc @RowlandBanks @JFCote wanna review?

2024-03-07 10:42 UTC, RowlandBanks requested changes

2024-03-07 10:42 UTC, RowlandBanks commented on docs/languages/Csharp.md
> +Note that, the `Equals` method uses `Object.Equals(objA, objB)`. This means that [reference types properties](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/reference-typ
nit: `Note that, the` → `Note that the`.

2024-03-07 10:42 UTC, RowlandBanks commented on docs/languages/Csharp.md
>  To generate auto-implemented properties (the ones with with `{ get; set; }` accessors), use the preset `CSHARP_COMMON_PRESET` and provide the option `autoImplementedProperties: true`
I realize this wasn't written by you, but can you fix the `with with` in this line 🙂? Thanks!

2024-03-07 13:32 UTC, RowlandBanks approved these changes

2024-03-08 09:09 UTC, jonaslagoni approved these changes
Thanks for taking the time @Louis-PhilippeGentile ✌️

2024-03-08 09:10 UTC, jonaslagoni commented
/rtm

2024-03-08 09:10 UTC, merged

2024-03-08 12:32 UTC, jonaslagoni commented
@all-contributors please add @Louis-PhilippeGentile for code, test, docs, bug