feat: export and import interfaces as types when using named imports and ESM Module Syntax
asyncapi/modelina pull request #1873
Opened 2024-03-09 23:58 UTC by moritzkalwa

## Description
When using modelType 'interface', exportType 'named' and moduleSystem 'ESM' export and import interfaces as types to support verbatimModuleSyntax.
This should not be a breaking change, interfaces are types even when not using verbatimModuleSyntax, explicitly marking them as types is optional in that case though.

## Related Issue
fixes #1793 

## Checklist
- [x] The code follows the project's coding standards and is properly linted (`npm run lint`).
- [x] Tests have been added or updated to cover the changes.
- [ ] Documentation has been updated to reflect the changes.
- [x] All tests pass successfully locally.(`npm run test`).

## Additional Notes
This PR also includes a change that makes sure only interfaces are imported/exported as types, as the previous version of this PR also exported enums as types.

2024-03-10 10:05 UTC, jonaslagoni requested changes
Gonna have to re-target to `next` because of the breaking changes to the dependency manager (it's exposed to users). Just need to make a quick update https://github.com/asyncapi/modelina/pull/1875 before I can do it.

Do you mind adding those changes to the migration docs: https://github.com/asyncapi/modelina/blob/next/docs/migrations/version-3-to-4.md

You should be able to merge `next` into your branch with no issues

2024-03-18 16:29 UTC, Samridhi-98 approved these changes

2024-03-24 15:24 UTC, moritzkalwa commented
> Gonna have to re-target to `next` because of the breaking changes to the dependency manager (it's exposed to users). Just need to make a quick update #1876 before I can do it.
> 
> Do you mind adding those changes to the migration docs: https://github.com/asyncapi/modelina/blob/next/docs/migrations/version-3-to-4.md
> 
> You should be able to easily merge `next` into your branch 🙂

Are you sure this needs to go into the migration guide? This should not break anything afaik, environments that haven't used verbatim module Syntax before should still work with interfaces now exported/imported as types and environments that do will now work without causing errors. 🤔 I could certainly add this into the migration guide, it feels wrong there though as there is no action required.

2024-03-24 19:28 UTC, jonaslagoni commented
> Are you sure this needs to go into the migration guide? This should not break anything afaik, environments that haven't used verbatim module Syntax before should still work with interfaces now exported/imported as types and environments that do will now work without causing errors.

Its not the new feature that is breaking, but the syntax of the dependency manager functions, which are public interface for people to use 🙂

2025-01-02 00:18 UTC, closed without merging