feat: go
asyncapi/modelina pull request #1939
Opened 2024-04-15 14:04 UTC by Souvikns

## Description

Adding support for nullable and required object for golang

## Related Issue

Fixes #1418

## Checklist
- [ ] The code follows the project's coding standards and is properly linted (`npm run lint`).
- [ ] Tests have been added or updated to cover the changes.
- [ ] Documentation has been updated to reflect the changes.
- [ ] All tests pass successfully locally.(`npm run test`).

## Additional Notes

2024-04-23 13:50 UTC, jonaslagoni requested changes

2024-04-23 13:50 UTC, jonaslagoni commented on src/generators/go/GoConstrainer.ts
> +  }
Do you mind simplifying this if statement?  - and its called `required` not `requried` 🙂

2024-04-23 13:50 UTC, jonaslagoni commented on test/generators/go/GoConstrainer.spec.ts
> +describe('nullable & requried properties', () => {
For simplicity, I would recommend merging this grouping of tests with the regular tests, i.e. you have 4 tests under `describe('String', () => {` to keep it simple and a single place to look for the tests for specific type.

2024-04-23 13:50 UTC, jonaslagoni commented on test/generators/go/GoGenerator.spec.ts
> +          street_name: [{ type: 'string' }, { type: 'null' }],
This is not valid JSON Schema 🤔

2024-04-24 13:58 UTC, jonaslagoni requested changes

2024-04-24 13:58 UTC, jonaslagoni commented on test/generators/go/GoConstrainer.spec.ts
> +          propertyName: ''
This needs to be an instance of ConstrainedObjectPropertyModel 🙂

2024-04-24 16:23 UTC, jonaslagoni approved these changes
Nice 👍

2024-04-24 16:24 UTC, jonaslagoni commented
/rtm

2024-04-24 16:46 UTC, Souvikns commented
@jonaslagoni black box testing is failing, what to do for that.

2024-04-25 08:38 UTC, jonaslagoni requested changes

2024-04-25 08:38 UTC, jonaslagoni commented on src/generators/go/GoConstrainer.ts
> +import { ConstrainedMetaModel, ConstrainedObjectPropertyModel } from 'models';
This needs to change to relative path instead of absolute 🙂

2024-04-25 09:42 UTC, jonaslagoni approved these changes
LGTM 👍

2024-04-25 09:43 UTC, merged