feat: adding support to change the collection type for arrays in Java models
asyncapi/modelina pull request #2029
Opened 2024-06-10 04:43 UTC by borrull

## Description
This PR adds support to change the collection type in Java models by introducing a new parameter "javaArrayType" to the generate models command.

## Checklist
- [x] The code follows the project's coding standards and is properly linted (`npm run lint`).
- [x] Tests have been added or updated to cover the changes.
- [x] Documentation has been updated to reflect the changes.
- [x] All tests pass successfully locally.(`npm run test`).

2024-06-10 05:57 UTC, borrull commented
Created this PR to implement the same as in https://github.com/asyncapi/cli/pull/1437 to address https://github.com/asyncapi/cli/issues/1436 , but being blocked by Sonar due to duplications on test file. Am I missing something here?

2024-06-10 06:27 UTC, jonaslagoni requested changes
Just one comment :v:

2024-06-10 06:27 UTC, jonaslagoni commented on modelina-cli/src/helpers/java.ts
> +    options: ['Array', 'List'],
```suggestion
    options: ['array', 'list'],
```

Lets keep it to all lower case or all upper case options for now :v:

2024-06-10 06:27 UTC, jonaslagoni commented on modelina-cli/src/helpers/java.ts
> +    default: 'Array'
```suggestion
    default: 'array'
```

2024-06-10 06:27 UTC, jonaslagoni commented on modelina-cli/src/helpers/java.ts
> +    collectionType: javaArrayType as 'Array' | 'List'
```suggestion
    collectionType: javaArrayType as 'array' | 'list'
```

2024-06-10 06:27 UTC, jonaslagoni commented on modelina-cli/test/integration/generate.test.ts
> +      .command([...generalOptions, 'java', ASYNCAPI_V2_DOCUMENT, `-o=${ path.resolve(outputDir, './java')}`, '--packageName', 'test.pkg', '--javaArrayType=List'])
```suggestion
      .command([...generalOptions, 'java', ASYNCAPI_V2_DOCUMENT, `-o=${ path.resolve(outputDir, './java')}`, '--packageName', 'test.pkg', '--javaArrayType=list'])
```

2024-06-10 07:03 UTC, jonaslagoni commented
> Created this PR to implement the same as in [asyncapi/cli#1437](https://github.com/asyncapi/cli/pull/1437) to address [asyncapi/cli#1436](https://github.com/asyncapi/cli/issues/1436) , but being blocked by Sonar due to duplications on test file. Am I missing something here?

Just ignore it 🙂

2024-06-11 07:43 UTC, jonaslagoni approved these changes
C# already use first upper case, so lets stick to it until we get uniform options :v:

2024-06-11 07:43 UTC, merged

2024-06-11 08:04 UTC, jonaslagoni commented
@all-contributors please add @borrull for code, test