feat: #2114 - add required field management in csharp newtonsoft serializer
asyncapi/modelina pull request #2117
Opened 2024-10-29 10:27 UTC by fr-th

## Description
When generating c# model with newtonsoft serialization, an option now allows to prevent deserialization if required fields are missing

## Related Issue
https://github.com/asyncapi/modelina/issues/2114 

## Checklist
- [x] The code follows the project's coding standards and is properly linted (`npm run lint`).
- [x] Tests have been added or updated to cover the changes.
- [x] Documentation has been updated to reflect the changes.
- [x] All tests pass successfully locally.(`npm run test`).

## Additional Notes

2024-10-29 10:46 UTC, jonaslagoni approved these changes
Do you want to continue with `enforceRequired` or make it part of the default rendering process?

All you need to make the changes on the `next` branch instead of `master`, but up to you 🙂

2024-10-29 10:46 UTC, jonaslagoni requested changes
** Still need to review 😄

2024-10-29 10:51 UTC, fr-th commented
Ah damn, I missed the part for the 'next' branch sorry. 
I'll adapt

2025-01-24 13:54 UTC, jonaslagoni commented
Lets just do master.

2025-01-25 12:13 UTC, jonaslagoni approved these changes

2025-01-25 12:46 UTC, merged

2025-01-25 12:46 UTC, jonaslagoni commented
@all-contributors please add @fr-th  for code, test, docs