Fix #1725: Added loading text
asyncapi/modelina pull request #2132
Opened 2024-11-30 14:46 UTC by Shriya-Chauhan

## Description
Added loader.

[Screencast from 11-30-2024 08:11:34 PM.webm](https://github.com/user-attachments/assets/dd5279ce-0af7-4eaa-ac41-0f5117cf5a08)

## Related Issue

## Checklist
- [ ] The code follows the project's coding standards and is properly linted (`npm run lint`).
- [ ] Tests have been added or updated to cover the changes.
- [ ] Documentation has been updated to reflect the changes.
- [ ] All tests pass successfully locally.(`npm run test`).

## Additional Notes

2024-11-30 14:50 UTC, Shriya-Chauhan commented
@devilkiller-ag I have created pr for resolving issue #1725 . Please take a look and let me know if any changes required.

2024-11-30 16:06 UTC, devilkiller-ag requested changes

2024-11-30 16:28 UTC, Shriya-Chauhan commented on modelina-website/src/components/playground/Playground.tsx
> +            setOutputLoading(true);
Ok! Working on this.

2024-12-01 11:10 UTC, Shriya-Chauhan commented on modelina-website/src/components/playground/Playground.tsx
> +      setOutputLoading(true);
Can you please review again. I have made the necessary changes @devilkiller-ag

2024-12-02 18:12 UTC, devilkiller-ag commented
/rtm

2024-12-02 18:13 UTC, merged

2024-12-02 19:23 UTC, Shriya-Chauhan commented
@devilkiller-ag Thank you for your support and guidance. I would love to contribute more—kindly point me to any other issues where I can help.

2024-12-04 16:39 UTC, devilkiller-ag commented
> @devilkiller-ag Thank you for your support and guidance. I would love to contribute more—kindly point me to any other issues where I can help.

You can try #1360. Besides this, we have also some issues related to Modelina tool which you can explore on the [issues](https://github.com/asyncapi/modelina/issues/) page.