feat: add namingConvention option and pass generator to renderers
asyncapi/modelina pull request #266
Opened 2021-06-22 11:40 UTC by jonaslagoni

**Description**

- Add `namingConvention` option to options: naming for type and single property
- Pass `generator` to `renderers`
- Add `collectionType` option to Java generator to render `List<type>` or `type[]` signature for collections
- Add unit tests
- Update renderers and use `namingConvention` everywhere
- Update docs

**Related issue(s)**
fixes https://github.com/asyncapi/generator-model-sdk/issues/124
fixes https://github.com/asyncapi/generator-model-sdk/issues/126

Hijacked from https://github.com/asyncapi/modelina/pull/129 as agreed with @magicmatatjahu

2021-06-22 11:52 UTC, magicmatatjahu commented
I don't know if it's a good idea to make review for my own (in 80-90%) code 😅 @smoya Could you also check PR as co-reviewer?

2021-06-22 11:58 UTC, jonaslagoni commented
> I don't know if it's a good idea to make review for my own (in 80-90%) code 😅 @smoya Could you also check PR as co-reviewer?

Gonna need to add some JSDoc to this, gonna request a review once it is ready

2021-06-22 12:18 UTC, jonaslagoni commented
Just occurred to me that, because each language might have different naming conventions, that will be called differently, this needs to be in the individual generators, and not in the AbstractGenerator... Example Go properties are called `fields` and with no way of defining that convention, this feature falls through..

2021-06-23 10:47 UTC, jonaslagoni commented on src/generators/java/JavaRenderer.ts
> +  }
While at the moment it looks like duplicate code, solving #176 will result in different implementations between renderers.

2021-06-23 10:51 UTC, jonaslagoni commented
@magicmatatjahu @smoya okay it is ready to be reviewed now 🙇

2021-07-05 13:03 UTC, magicmatatjahu requested changes
We should also add the `namingConvention` for the Golang generator :)

2021-07-05 13:03 UTC, magicmatatjahu commented on src/generators/java/JavaRenderer.ts
> +    ) {
```suggestion
    const kind = TypeHelpers.extractKind(model);
    if (
      kind === ModelKind.PRIMITIVE ||
      kind === ModelKind.ARRAY
    ) {
```

2021-07-05 14:17 UTC, jonaslagoni commented
> We should also add the `namingConvention` for the Golang generator :)

Done, completely forgot about it 😆 Updated docs and Go generator.

2021-07-05 14:52 UTC, magicmatatjahu commented on src/helpers/NameHelpers.ts
> +  property?: (name: string | undefined, ctx: { model: CommonModel, inputModel: CommonInputModel, property?: CommonModel }) => string;
Sorry I didn't notice it 😅

2021-07-05 14:56 UTC, magicmatatjahu approved these changes
LGTM!

2021-07-05 15:51 UTC, merged