test: add multiple blackbox tests
asyncapi/modelina pull request #371
Opened 2021-09-14 14:59 UTC by jonaslagoni

**Description**
As we start to integrate more and more inputs, it is important that each work as expected. This PR adds all those documents to a single blackbox test.

It adds the following documents:
- AsyncAPI 2.0 and 2.1
    - dummy documents
- JSON Schema draft 4 
    - swagger-2_0.json - The entire Swagger 2.0 schema document
- JSON Schema draft 7
    - asyncapi-2_0.json - The entire AsyncAPI 2.0 schema document
    - dummy.json - Some dummy JSON Schema document
    - github-action.json - The JSON Schema document for github actions
    - github-workflow.json - The JSON Schema document for github workflows
    - gitlab-ci.json - The JSON Schema document for gitlab CI
- Swagger 2.0
    - The general petstore example

2021-09-27 11:14 UTC, magicmatatjahu requested changes

2021-09-27 11:14 UTC, magicmatatjahu commented on src/generators/java/JavaGenerator.ts
> +    //We dont support union in Go generator, however, if union is an object, we render it as a struct.
```suggestion
    // We don't support union in Java generator, however, if union is an object, we render it as a class.
```

2021-09-27 11:14 UTC, magicmatatjahu commented on src/generators/go/GoGenerator.ts
> +      //We dont support union in Go generator, however, if union is an object, we render it as a struct.
```suggestion
      // We don't support union in Go generator, however, if union is an object, we render it as a struct.
```

2021-09-27 11:14 UTC, magicmatatjahu commented on test/blackbox/README.md
> +- To to run the `C#` BlackBox tests, you need to have C# compiler installed globally. - https://www.mono-project.com/download/stable/
Please also add info about `Go` language :)

2021-09-27 11:16 UTC, jonaslagoni commented on test/blackbox/README.md
> +- To to run the `C#` BlackBox tests, you need to have C# compiler installed globally. - https://www.mono-project.com/download/stable/
🤦 right!

2021-09-27 11:44 UTC, magicmatatjahu approved these changes
For me, it looks good. @alequetzalli Do you want to make review of changed mds?

2021-09-27 18:30 UTC, alequetzalli commented on docs/development.md
> +We have a bunch of BlackBox tests, that are run separately to the `npm run test` script. Please refer to the [BlackBox documentation](../test/blackbox) for further information.
```suggestion
We have several BlackBox tests that are run separately from the `npm run test` script. Please refer to the [BlackBox documentation](../test/blackbox) for further information.
```

2021-09-27 18:33 UTC, alequetzalli commented on test/blackbox/README.md
> +As we start to integrate more and more inputs, it is important that we test actual real inputs from users to ensure that the library behaves as expected. The best way I can see is to add them as Blac
```suggestion
As we start to integrate more and more inputs, it is important that we test actual and real inputs from users to ensure the library behaves as expected. For now, the best way is to add them as BlackBox tests. The BlackBox tests are focused on catching syntax errors and not logical errors, although they can be manually used for this.
```

2021-09-27 18:34 UTC, alequetzalli commented on test/blackbox/README.md
> +By default the BlackBox tests are not run with the regular `npm run test`, but can be run with `npm run test:blackbox`.
```suggestion
By default, the BlackBox tests are not run with the regular `npm run test`, but can be run with `npm run test:blackbox`.
```

2021-09-27 18:35 UTC, alequetzalli commented
> For me, it looks good. @alequetzalli Do you want to make review of changed mds?

dun dun dun... Poor @jonaslagoni 😂.. yes! I accept and gave a succint review! 😆😀🦄✨✨

2021-09-27 19:15 UTC, alequetzalli approved these changes
LGTM 🚀 ✨✨✨

2021-09-28 08:28 UTC, magicmatatjahu approved these changes

2021-09-28 08:43 UTC, merged