fix: Non-required properties are required by constructor
asyncapi/modelina pull request #553
Opened 2022-01-03 21:33 UTC by mahakporwal02

**Description**
The JavaScript generator created constructors that requires non-required properties.
Added a filter function that only filters required properties.

**Related issue(s)**
Fixes #538

2022-01-03 21:39 UTC, mahakporwal02 commented
@jonaslagoni I just realised one of the tests is failing. I'll update the test later today.

2022-01-04 19:31 UTC, jonaslagoni commented
You can update the changed snapshots with `npm run test -- -u` 🙂

2022-01-05 20:26 UTC, mahakporwal02 commented
@jonaslagoni Sorry I missed your previous comment and changed the tests by updating the test cases instead of the snapshots.
Kindly have a look if this works or should I anyway update the snapshots only?

2022-01-06 15:44 UTC, jonaslagoni requested changes
Just have a small suggestion, otherwise it looks good 👍 🙂

2022-01-06 15:44 UTC, jonaslagoni commented on examples/javascript-use-cjs/index.ts
> +      required: ['email']
To stay consistent I don't think we should add anything unnecessary to the inputs, as you already have a test in the JavaScriptGenerator 🙂

2022-01-06 15:44 UTC, jonaslagoni commented on examples/generate-javascript-models/index.ts
> +  required: ['email'],
To stay consistent I don't think we should add anything unnecessary to the inputs, as you already have a test in the JavaScriptGenerator 🙂

2022-01-06 15:44 UTC, jonaslagoni commented on examples/javascript-use-esm/index.ts
> +      required: ['email'],
To stay consistent I don't think we should add anything unnecessary to the inputs, as you already have a test in the JavaScriptGenerator 🙂

2022-01-06 15:44 UTC, jonaslagoni commented on examples/javascript-use-esm/index.ts
> +  required: ['person'],
To stay consistent I don't think we should add anything unnecessary to the inputs, as you already have a test in the JavaScriptGenerator 🙂

2022-01-06 15:44 UTC, jonaslagoni commented on examples/javascript-use-cjs/index.ts
> +  required: ['person']
To stay consistent I don't think we should add anything unnecessary to the inputs, as you already have a test in the JavaScriptGenerator 🙂

2022-01-07 13:54 UTC, jonaslagoni approved these changes
Perfect 🎉

2022-01-07 13:55 UTC, jonaslagoni commented
!rtm

2022-01-07 14:01 UTC, jonaslagoni commented
👀 Well, it should not complain about that... Gonna need to figure out why it complains

2022-01-10 20:41 UTC, merged

2022-01-11 09:59 UTC, jonaslagoni commented
@all-contributors please add @mahakporwal02 for code