docs: example on how to include a custom function in the data model
asyncapi/modelina pull request #566
Opened 2022-01-08 13:43 UTC by mahakporwal02

**Description**
Added example on how to include custom function in data model.
https://github.com/mahakporwal02/modelina/tree/issue-413/examples/include-custom-function
Updated documentation.
https://github.com/mahakporwal02/modelina/blob/issue-413/examples/include-custom-function/README.md
https://github.com/mahakporwal02/modelina/blob/issue-413/examples/README.md
https://github.com/mahakporwal02/modelina/blob/issue-413/docs/advanced.md

**Related issue(s)**
#413

2022-01-10 14:00 UTC, jonaslagoni requested changes
Got a few comments, otherwise looks good 👍

2022-01-10 19:35 UTC, mahakporwal02 commented on docs/advanced.md
> +This can be done through a custom preset using the hook additionalContent.
Definitely.

2022-01-11 08:51 UTC, mahakporwal02 commented
@jonaslagoni `examples/generate-to-files/index.spec.ts` test passes in my local repository. I don't know why it is failing here.

2022-01-11 09:26 UTC, jonaslagoni requested changes
Just to more changes 🙂 

Regarding the tests not passing, it should be resolved now.

2022-01-11 09:26 UTC, jonaslagoni commented on examples/include-custom-function/README.md
> +# TODO: Custom Function
```suggestion
# Custom Function
```

2022-01-11 09:26 UTC, jonaslagoni commented on examples/README.md
> +- [custom-function](./custom-logging) - A basic example where a custom function is included.
```suggestion
- [include-custom-function](./include-custom-function) - A basic example where a custom function is included.
```

2022-01-11 09:47 UTC, jonaslagoni approved these changes
LGTM 👍 Awesome 🎉

2022-01-11 09:47 UTC, jonaslagoni commented
/rtm

2022-01-11 09:50 UTC, merged