feature: added nvmrc
asyncapi/modelina pull request #582
Opened 2022-01-13 14:34 UTC by ritik307

**Description**
- Added command to implement and install `.nvmrc`.
- Updated `docs/development.md` with the commands to setup `.nvmrc`  

**Related issue(s)**
Resolves #575

2022-01-13 14:36 UTC, ritik307 commented
@fmvilas @derberg @ron-debajyoti  kindly review the PR

2022-01-13 14:57 UTC, ron-debajyoti commented
> @fmvilas @derberg @ron-debajyoti kindly review the PR

I'm not a maintainer tbh, just another fellow contributor :smile:   @jonaslagoni would the main guy here.

2022-01-14 12:35 UTC, jonaslagoni reviewed
@ritik307 is there any reason you see us needing the script `nvmrc` rather than just committing that file? That way the steps others need to do it only `nvm use` 🤔

2022-01-14 13:20 UTC, ritik307 commented
> @ritik307 Thanks for taking the time to do this +1
> 
> One question, is there any reason you see us needing the script `nvmrc` rather than just committing that file? That way the steps others need to do it only `nvm use` thinking

I think it better bcz there won't be a need for a dev to have nvm already installed in their machine and also if a dev doesn't require nvmrc file they still have to keep it in the root folder regardless. I don't have any problem switching to the way you are thinking to implement this I will update the PR accordingly.

2022-01-14 13:23 UTC, jonaslagoni commented
> I think the implemented approach is better bcz there won't be a need for a dev to have nvm already installed in their machine and also if a dev doesn't require nvmrc file they still have to keep it in the root folder regardless

Regardless of this approach or the other, would they not need `nvm` installed anyway? 

The only difference I see is that, with your script, we can "dynamically` create the appropriate nvmrc file. However, as the node requirement wont really change, having it hardcoded might be a better fit 🙂

2022-01-14 13:58 UTC, ritik307 commented
> > I think the implemented approach is better bcz there won't be a need for a dev to have nvm already installed in their machine and also if a dev doesn't require nvmrc file they still have to keep it in the root folder regardless
> 
> Regardless of this approach or the other, would they not need `nvm` installed anyway?
> 
> The only difference I see is that, with your script, we can "dynamically` create the appropriate nvmrc file. However, as the node requirement wont really change, having it hardcoded might be a better fit slightly_smiling_face

Done! kindly review

2022-01-14 14:56 UTC, jonaslagoni requested changes
Got a few follow up questions 🙂 

Also for the title of the PR, please use `chore:` as this is not a feature for the library, but a feature for the development setup 🙂

2022-01-14 15:05 UTC, ritik307 commented on .nvmrc
> +v14.18.2
I am not sure about the hardcode common practice but I am sure that v14 would be enough and supported

2022-01-14 18:03 UTC, jonaslagoni commented on .nvmrc
> +v14.18.2
Let's try with only hardcoding the major version, for now, that way we take full advantage of node 🙂 
```suggestion
v14
```

2022-01-14 18:09 UTC, ritik307 commented on .nvmrc
> +v14.18.2
done!

2022-01-14 18:09 UTC, ritik307 commented on docs/development.md
> +2. Run `nvm use` to update the nodejs version.
Done!

2022-01-14 18:11 UTC, jonaslagoni approved these changes
LGTM! 🎉

2022-01-14 18:11 UTC, jonaslagoni commented
/rtm

2022-01-14 18:49 UTC, merged

2022-01-14 18:51 UTC, jonaslagoni commented
@all-contributors please add @ritik307 for doc