feat: Assign optional/non required arguments in the constructor if pr…
asyncapi/modelina pull request #586
Opened 2022-01-14 10:18 UTC by mahakporwal02

Enhancement to javascript generator to assign optional/non required arguments in the constructor during object formation.

**Related issue(s)**
#581

2022-01-14 11:02 UTC, mahakporwal02 commented
@jonaslagoni Kindly review the PR.

2022-01-14 12:32 UTC, jonaslagoni requested changes

2022-01-14 12:32 UTC, jonaslagoni commented on examples/generate-javascript-models/__snapshots__/index.spec.ts.snap
> +    if (input.hasOwnProperty(email)) {
This will throw an error when used, as there is no variable called `email` 🙂

2022-01-14 13:37 UTC, jonaslagoni commented on examples/generate-javascript-models/__snapshots__/index.spec.ts.snap
> +    if (input.hasOwnProperty(email)) {
Please do yes 😄

2022-01-15 13:39 UTC, jonaslagoni approved these changes
LGTM! 🎉

2022-01-15 13:39 UTC, jonaslagoni commented
/rtm

2022-01-15 14:40 UTC, merged