feat: Add JSDoc style comment support to Typescript generator
asyncapi/modelina pull request #621
Opened 2022-02-08 17:00 UTC by gabormagyar

Might need tests; tests for comment generation are already included just not for them being included. Don't think it needs docs as the feature is automatic and self explanatory.

Make sure to filter whitespace changes when viewing diff.

2022-02-09 10:15 UTC, jonaslagoni requested changes
Small specific comment, also remember to add tests to ensure it works as intended 👍 

It seems you might have auto-formatting enabled in your development environment making unnecessary changes that make it harder to review, do you mind disabling it and re-commit the intended changes? 🙂

2022-02-09 10:15 UTC, jonaslagoni commented on src/generators/typescript/TypeScriptRenderer.ts
> +    const formattedDoc = desc || examples ? `${doc}\n` : '';
Remember, any of these properties fetched from the original input might not exist at all, so to use them you need extensive checks ensuring that you find anything 🙂

2022-02-09 12:14 UTC, gabormagyar commented
Auto formatting removed

2022-03-02 18:11 UTC, jonaslagoni commented
@gabormagyar sorry I did not caught this the first time, this has to be added as a preset instead, similar to what is being done here: https://github.com/asyncapi/modelina/pull/649 and what we have for Java https://github.com/asyncapi/modelina/blob/master/docs/languages/Java.md#include-javadoc-for-properties already.

We need to remember, that it's up to the users how the output model should sticked together 🙂

2022-03-07 09:09 UTC, gabormagyar commented
@jonaslagoni Please re-review

2022-03-07 09:15 UTC, jonaslagoni requested changes
Looks good 👍 

We are only missing an example and updating the documentation: https://github.com/asyncapi/modelina/blob/master/docs/languages/JavaScript.md

Otherwise there are no easy way for others to know about it 🙂

2022-03-07 09:36 UTC, Samridhi-98 requested changes
@gabormagyar  Please add `typscript-generate-comment` [here](https://github.com/asyncapi/modelina/tree/master/examples#readme). 😊

2022-03-07 09:37 UTC, jonaslagoni reviewed
That was quick ⏩!

This looks good to me 👍

2022-03-07 09:44 UTC, Samridhi-98 commented
> That was quick ⏩!
> 
> This looks good to me 👍
> 
> @Samridhi-98 do you want to make a review as well?

I checked rest looks good to me 🙂

2022-03-07 09:45 UTC, Samridhi-98 submitted a review, later dismissed
🎉

2022-03-07 09:50 UTC, jonaslagoni commented
Got some linting problems 🙂

2022-03-07 10:04 UTC, Samridhi-98 approved these changes

2022-03-07 10:10 UTC, Samridhi-98 commented
/rtm

2022-03-07 10:38 UTC, jonaslagoni approved these changes

2022-03-09 08:24 UTC, Samridhi-98 commented
/rtm

2022-03-09 08:25 UTC, merged

2022-03-09 13:15 UTC, Samridhi-98 commented
@all-contributors please add @gabormagyar  for code, test, docs, example