feat: added example in js
asyncapi/modelina pull request #629
Opened 2022-02-11 06:07 UTC by Samridhi-98

**Description**

-  Added `example` option in `javascript/commonpreset.ts`
- Modified `docs/language/javascript`
- Added test for `example` option

**Related issue(s)**

Fixes #625

2022-02-13 05:30 UTC, Samridhi-98 commented
@jonaslagoni  please review my PR 🙂

2022-02-13 11:30 UTC, jonaslagoni requested changes
Do you mind splitting this into two PR's? Cause if we ever have to rollback the example feature, we would need to rollback the marshalling example as well, which is not preferred 😄

2022-02-13 12:34 UTC, Samridhi-98 commented
@jonaslagoni  Sure, will do it.

2022-02-14 11:59 UTC, jonaslagoni requested changes
Hahaha, I had to review make sure I did not ask you to remove the example for the feature just to ask you to add it again 😆 

Remember to create `example` as well as add the documentation for https://github.com/asyncapi/modelina/blob/master/docs/languages/JavaScript.md 🙂

2022-02-14 13:52 UTC, Samridhi-98 commented
> Hahaha, I had to review make sure I did not ask you to remove the example for the feature just to ask you to add it again 😆
> 
> Remember to create `example` as well as add the documentation for https://github.com/asyncapi/modelina/blob/master/docs/languages/JavaScript.md 🙂

Sorry, I misunderstood it.
I have opened another PR for `examples`  🙂

2022-02-14 13:54 UTC, jonaslagoni commented
> Sorry, I misunderstood it. I have opened another PR for `examples` 🙂

You did not misunderstand anything 🙂 The example you have added in your PR, is the one about marshalling right? 

In this PR, we need an example for the `example` preset you have added 🙂

2022-02-14 14:15 UTC, Samridhi-98 commented
> 

Oh, yeah mistakenly I had added a marshaling example in this PR. 😅

2022-02-15 10:12 UTC, jonaslagoni requested changes
Only one small change 💪

2022-02-15 10:12 UTC, jonaslagoni commented on test/generators/javascript/preset/utils/ExampleFunctions.spec.ts
> +describe('Marshalling preset', () => {
Did you mean something else here? 🙂

2022-02-15 12:21 UTC, Samridhi-98 commented on test/generators/javascript/preset/utils/ExampleFunctions.spec.ts
> +describe('Marshalling preset', () => {
Sorry, it's a typo `Example preset` 😅

2022-02-15 12:28 UTC, jonaslagoni approved these changes
LGTM 🎉

2022-02-15 12:28 UTC, jonaslagoni commented
/rtm

2022-02-15 12:39 UTC, merged