add method to render as const enums values for go generator
asyncapi/modelina pull request #662
Opened 2022-03-02 12:49 UTC by ibernabeudev

**Description**

- Added a new method to render enum values as const for Go generator
- Works for integer (using iota) or strings

**Related issue(s)**
`See also #647 `

2022-03-07 08:15 UTC, jonaslagoni commented
Thanks for taking the time to add this @ibernabeudev!

@smoya would you be able to take a look at the Go output? 🙂

2022-03-07 10:01 UTC, smoya commented on examples/generate-go-enums/__snapshots__/index.spec.ts.snap
> +const (
Nitpick: Would it make sense to add a comment here such as: 
```suggestion
// These are all the valid values for Cities enum.
const (
```

In that way, Godoc documentation will add an extra context, useful IMHO:

```bash 
❯ go doc -all main.go


CONSTANTS

const (
        London    Cities = "London"
        Rome             = "Rome"
        Brusseles        = "Brusseles"
)
    These are all the valid values for Cities enum.


TYPES

type Cities string
    Cities represents an enum of string.
```

2022-03-07 10:08 UTC, smoya commented on examples/generate-go-enums/README.md
> +A basic example of how to Modelina render enums values in Go.
```suggestion
A basic example of how Modelina renders enum values in Go.
```

2022-03-07 10:08 UTC, smoya reviewed
Thanks for your work here @ibernabeudev ! 💯 🚀 

Go output code seems ok to me 👍  Just wrote a nitpick.
JS part review is pending by other folks.

2022-03-09 18:45 UTC, ibernabeudev commented
Thanks @smoya for your feedback I commit your suggestions. 

I just add a minor change to generate the const names with the type as first word (camel case) to avoid possible collisions when you have different name type enums but with an equal shared value, also I think this is how it was expected to works in the initial issue.

2022-03-14 12:00 UTC, jonaslagoni reviewed
Do you mind adding the example to https://github.com/asyncapi/modelina/tree/master/examples ? 🙂 

You also have some linting errors 🙂 

Otherwise, it looks good to me 👍

2022-03-15 20:17 UTC, jonaslagoni commented
/rtm

2022-03-15 20:19 UTC, jonaslagoni requested changes
You have some linting errors 🙂

2022-03-15 20:55 UTC, ibernabeudev commented
> You have some linting errors 🙂

Fixed, I rewrite the render method because I was having a  **Generic Object Injection Sink (security/detect-object-injection).** annoying linter error.

Also, I added notation **eslint-disable-next-line sonarjs/no-duplicate-string** on line 15 because I saw we used it in another file to avoid have to extract the literal "interface{}" (I think we want to be explicit for these cases).

2022-03-21 12:05 UTC, jonaslagoni commented
> Fixed, I rewrite the render method because I was having a **Generic Object Injection Sink (security/detect-object-injection).** annoying linter error.

Don't disable them 🙂 You can use `String(xxx)` to fix it.

2022-03-21 12:12 UTC, jonaslagoni approved these changes
LGTM 👍

2022-03-21 12:13 UTC, jonaslagoni requested changes
I see the blackbox tests caught a problem 🙂

2022-04-05 19:42 UTC, ibernabeudev commented
> I see the blackbox tests caught a problem 🙂
Hi, sorry I was a bit busy these weeks. I fixed the blackbox test error. 

Also I saw a problem with the dockerfile for build the image that runs this test but you can easily solve adding two lines before copy the package-lock.json from hosts to container.

```
....
# Setup library 
WORKDIR /usr/app
COPY package.json .
COPY package-lock.json .
RUN npm install
COPY . .
```

In fact, you could move the last **COPY** command to the next line after **WORKDIR** under the comment **Setup library** and delete the others COPY lines saving two docker layers I think. 

I didn't add this fix to the MR because I don't know if this is correct and I suppose this must be place in another PR.

2022-04-11 10:04 UTC, jonaslagoni commented
/rtm

2022-04-11 13:12 UTC, jonaslagoni approved these changes

2022-04-11 13:14 UTC, merged

2022-04-11 13:20 UTC, jonaslagoni commented
@all-contributors please add @ibernabeudev for code, test, example, docs