feat: support AsyncAPI v2.4.0
asyncapi/modelina pull request #733
Opened 2022-04-26 15:04 UTC by owais34

**Description**
AsyncAPI v2.4.0 readiness

Test Results :

> cross-env CI=true jest --coverage --testPathIgnorePatterns ./test/blackbox --testPathIgnorePatterns ./examples/TEMPLATE

Browserslist: caniuse-lite is outdated. Please run:
  npx browserslist@latest --update-db
  Why you should do it regularly: https://github.com/browserslist/browserslist#browsers-data-updating
Browserslist: caniuse-lite is outdated. Please run:
  npx browserslist@latest --update-db
  Why you should do it regularly: https://github.com/browserslist/browserslist#browsers-data-updating
Browserslist: caniuse-lite is outdated. Please run:
  npx browserslist@latest --update-db
  Why you should do it regularly: https://github.com/browserslist/browserslist#browsers-data-updating
Browserslist: caniuse-lite is outdated. Please run:
  npx browserslist@latest --update-db
  Why you should do it regularly: https://github.com/browserslist/browserslist#browsers-data-updating
Browserslist: caniuse-lite is outdated. Please run:
  npx browserslist@latest --update-db
  Why you should do it regularly: https://github.com/browserslist/browserslist#browsers-data-updating
Browserslist: caniuse-lite is outdated. Please run:
  npx browserslist@latest --update-db
  Why you should do it regularly: https://github.com/browserslist/browserslist#browsers-data-updating
Browserslist: caniuse-lite is outdated. Please run:
  npx browserslist@latest --update-db
  Why you should do it regularly: https://github.com/browserslist/browserslist#browsers-data-updating
 PASS  test/models/Draft7Schema.spec.ts (8.655 s)
 PASS  test/models/CommonModel.spec.ts (10.963 s)
 PASS  test/processors/JsonSchemaInputProcessor.spec.ts (12.352 s)
 PASS  test/interpreter/unit/InterpretNot.spec.ts
 PASS  test/interpreter/unit/Intepreter.spec.ts
 PASS  test/generators/javascript/JavaScriptGenerator.spec.ts (17.143 s)
 PASS  test/interpreter/PostInterpreter.spec.ts (30.633 s)
 PASS  test/generators/java/JavaGenerator.spec.ts (30.667 s)
 PASS  test/generators/go/GoGenerator.spec.ts (22.059 s)
 PASS  test/generators/csharp/CSharpGenerator.spec.ts (17.221 s)
 PASS  test/generators/typescript/TypeScriptGenerator.spec.ts (30.779 s)
 PASS  test/generators/typescript/preset/MarshallingPreset.spec.ts (31.068 s)
 PASS  test/models/OpenAPIV3Schema.spec.ts
 PASS  test/processors/AsyncAPIInputProcessor.spec.ts
 PASS  test/models/SwaggerV2Schema.spec.ts
 PASS  test/generators/csharp/CSharpRenderer.spec.ts
 PASS  test/processors/InputProcessor.spec.ts
 PASS  test/generators/java/presets/CommonPreset.spec.ts
 PASS  test/utils/LoggingInterface.spec.ts
 PASS  test/generators/AbstractRenderer.spec.ts
 PASS  test/interpreter/unit/InterpretItems.spec.ts
 PASS  test/interpreter/unit/InterpretAllOf.spec.ts
 PASS  test/helpers/FormatHelpers.spec.ts
 PASS  test/generators/java/JavaRenderer.spec.ts
 PASS  test/interpreter/unit/Utils.spec.ts
 PASS  test/models/AsyncapiV2Schema.spec.ts
 PASS  test/generators/AbstractGenerator.spec.ts
 PASS  test/generators/typescript/TypeScriptRenderer.spec.ts
 PASS  test/interpreter/unit/InterpretAdditionalProperties.spec.ts
 PASS  test/processors/OpenAPIInputProcessor.spec.ts
 PASS  test/generators/typescript/preset/utils/ExampleFunctions.spec.ts
 PASS  test/interpreter/unit/InterpretAdditionalItems.spec.ts
 PASS  test/processors/SwaggerInputProcessor.spec.ts
 PASS  test/interpreter/unit/InterpretProperties.spec.ts
 PASS  test/generators/go/GoRenderer.spec.ts
 PASS  test/interpreter/unit/patternProperties.spec.ts
 PASS  test/helpers/NameHelpers.spec.ts
 PASS  test/generators/javascript/preset/utils/ExampleFunctions.spec.ts
 PASS  test/models/Draft4Schema.spec.ts
 PASS  test/models/Draft6Schema.spec.ts
 PASS  test/generators/javascript/JavaScriptFileGenerator.spec.ts
 PASS  test/generators/java/presets/DescriptionPreset.spec.ts
 PASS  test/generators/typescript/TypeScriptFileGenerator.spec.ts
 PASS  test/interpreter/unit/InterpretEnum.spec.ts
 PASS  test/interpreter/unit/InterpretDependencies.spec.ts
 PASS  test/interpreter/unit/InterpretConst.spec.ts
 PASS  test/models/OutputModel.spec.ts
 PASS  test/helpers/TypeHelpers.spec.ts
 PASS  test/generators/java/presets/ConstraintsPreset.spec.ts
 PASS  test/generators/csharp/CSharpFileGenerator.spec.ts
 PASS  test/generators/java/JavaFileGenerator.spec.ts
 PASS  test/generators/java/presets/JacksonPreset.spec.ts
 PASS  test/generators/javascript/JavaScriptRenderer.spec.ts
 PASS  test/helpers/FileHelpers.spec.ts
 PASS  test/generators/csharp/presets/CommonPreset.spec.ts
 PASS  test/generators/csharp/presets/JsonSerializerPreset.spec.ts
 PASS  test/generators/javascript/preset/MarshallingPreset.spec.ts
 PASS  test/generators/typescript/preset/DescriptionPreset.spec.ts
 PASS  test/models/RenderOutput.spec.ts
 PASS  test/generators/javascript/preset/ExamplePreset.spec.ts
 PASS  test/generators/typescript/preset/ExamplePreset.spec.ts
 PASS  examples/typescript-enum-type/index.spec.ts
 PASS  test/generators/typescript/renderers/EnumRenderer.spec.ts
 PASS  test/interpreter/Intepreter.spec.ts
 PASS  examples/generate-to-files/index.spec.ts
 PASS  examples/custom-logging/index.spec.ts
 PASS  examples/generate-go-enums/index.spec.ts
 PASS  examples/typescript-use-esm/index.spec.ts
 PASS  examples/javascript-use-esm/index.spec.ts
 PASS  examples/swagger2.0-from-object/index.spec.ts
 PASS  examples/typescript-use-cjs/index.spec.ts
 PASS  examples/openapi-from-object/index.spec.ts
 PASS  examples/csharp-generate-serializer/index.spec.ts
 PASS  examples/javascript-use-cjs/index.spec.ts
 PASS  examples/adapting-input-and-output/index.spec.ts
 PASS  examples/javascript-generate-marshalling/index.spec.ts
 PASS  examples/csharp-generate-equals-and-hashcode/index.spec.ts
 PASS  examples/typescript-generate-marshalling/index.spec.ts
 PASS  examples/java-generate-marshalling/index.spec.ts
 PASS  examples/java-generate-tostring/index.spec.ts
 PASS  examples/java-generate-hashcode/index.spec.ts
 PASS  examples/java-generate-equals/index.spec.ts
 PASS  examples/indentation-type-and-size/index.spec.ts
 PASS  examples/javascript-generate-example/index.spec.ts
 PASS  examples/typescript-generate-example/index.spec.ts
 PASS  examples/csharp-auto-implemented-properties/index.spec.ts
 PASS  examples/csharp-change-collection-type/index.spec.ts
 PASS  examples/java-generate-jackson-annotation/index.spec.ts
 PASS  examples/json-schema-draft7-from-object/index.spec.ts
 PASS  examples/java-change-collection-type/index.spec.ts
 PASS  examples/asyncapi-from-parser/index.spec.ts (5.11 s)
 PASS  examples/asyncapi-from-object/index.spec.ts
 PASS  examples/generate-javascript-models/index.spec.ts
 PASS  examples/include-custom-function/index.spec.ts
 PASS  examples/typescript-interface/index.spec.ts
 PASS  examples/generate-csharp-models/index.spec.ts
 PASS  examples/java-generate-javax-constraint-annotation/index.spec.ts
 PASS  examples/generate-typescript-models/index.spec.ts
 PASS  examples/typescript-generate-comments/index.spec.ts
 PASS  examples/generate-java-models/index.spec.ts
 PASS  examples/java-generate-javadoc/index.spec.ts
 PASS  examples/generate-go-models/index.spec.ts
 PASS  test/processors/TypeScriptInputProcessor.spec.ts (25.654 s)
 PASS  examples/java-from-typescript-type-with-options/index.spec.ts (22.731 s)
 PASS  examples/java-from-typescript-type/index.spec.ts (18.412 s)
-----------------------------------------|---------|----------|---------|---------|--------------------------------------
File                                     | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s
-----------------------------------------|---------|----------|---------|---------|--------------------------------------
All files                                |   96.94 |    86.15 |   96.72 |   97.37 | 
 src                                     |     100 |      100 |     100 |     100 | 
  index.ts                               |     100 |      100 |     100 |     100 | 
 src/generators                         [...]

2022-04-27 02:54 UTC, owais34 commented
@jonaslagoni the streetlights-operation-security.yml file to be placed in which folder ?

2022-04-27 02:56 UTC, jonaslagoni commented
> @jonaslagoni the streetlights-operation-security.yml file to be placed in which folder ?

In the 2.4 folder, as it uses the new operation security model 🙂

2022-04-27 02:58 UTC, jonaslagoni commented
Do you mind converting it to JSON btw? Don't think the BlackBox test setup can handle YAML 😄

2022-04-27 08:25 UTC, owais34 commented
@jonaslagoni  Sure will do

2022-04-27 08:42 UTC, owais34 commented
@jonaslagoni done

2022-04-27 23:29 UTC, jonaslagoni requested changes
@owais34 do you mind rebase with master and upgrade the parser to `1.15` that should automatically fix the blackbox tests that are failing 🙂

2022-04-28 04:45 UTC, owais34 commented
@jonaslagoni  I think that should do it hopefully , this was quite a learning experience  😁.

2022-04-28 14:20 UTC, jonaslagoni commented on test/blackbox/docs/AsyncAPI-2_4/streetlights-operation-security.json
> +          }
The security keyword expects an array 🙂 Take a look here: https://github.com/asyncapi/spec/blob/65d58696f8c3ab6471aa48b12d878221b8d8109e/examples/streetlights-operation-security.yml#L64
```suggestion
          "security": [{
            "streetlights_auth": [
              "streetlights:write"
            ]
          }]
```

You need to apply this to the rest of the channels 🙂

2022-04-29 12:37 UTC, owais34 commented
@jonaslagoni  yesssss!!!!🤩

2022-04-29 13:25 UTC, merged

2022-04-29 13:34 UTC, jonaslagoni commented
@all-contributors please add @owais34 for code, test, docs