refactor:Ensure that processorOptions is passed via constructor
asyncapi/modelina pull request #920
Opened 2022-10-03 18:06 UTC by artur-ciocanu

**Description**
This is a small refactoring PR to ensure that all the `processors` have access to `processorOptions` which is passed via constructor. Currently `processorOptions` is passed as a parameter to `process()` method, while we could go with this model, having all the dependencies passed via constructor allows to instantiate all the necessary objects as early as possible.

This should allow us to further customize the instantiation of `Interpreter` by passing the `interpreterOptions`. The general idea is to add `interpreterOptions` to `processorOptions` and the when instantiating the `Interpreter` we should be able to use something like:
```
new Interpreter(this.options.interpreterOptions); // options here is of type ProcessorOptions
```

**Related issue(s)**
https://github.com/asyncapi/modelina/issues/916

2022-10-03 18:22 UTC, artur-ciocanu commented
@jonaslagoni @ron-debajyoti @magicmatatjahu could someone provide some pointers on how to fix the "Blackbox testing". Thank you.

2022-10-03 18:28 UTC, jonaslagoni commented
> @jonaslagoni @ron-debajyoti @magicmatatjahu could someone provide some pointers on how to fix the "Blackbox testing". Thank you.

You can ignore them, for now and just focus on the other CI checks 🙂 I am trying to solve them here #905

2022-10-04 10:02 UTC, jonaslagoni reviewed
@artur-ciocanu I am gonna review this later today or tomorrow.

2022-10-05 13:59 UTC, jonaslagoni requested changes
For your purpose in regards to https://github.com/asyncapi/modelina/issues/916 do you mind clarifying why you want this change instead of letting the `process` functions carry the options around?

Cause with this change you end up creating a new instance per generator, instead of relying on the static instance. And I don't see the clear benefits, especially since you HAVE to provide it here anyway:  https://github.com/asyncapi/modelina/blob/21ce51034f8c0e16bd7eea21f29dc695bc1b0e42/src/processors/JsonSchemaInputProcessor.ts#L313

And so forth for all the processors that call the function. So I don't really see the need to change the architecture of this without further discussing it in an issue that proposes the change 🙂

2022-10-07 11:37 UTC, artur-ciocanu commented
@jonaslagoni thanks a lot for your feedback and review. I have changed the approach to pass `processorOptions` to `processor.process()` and ensure that `interpreterOptions` is passed to `JsonSchemaInputProcessor.convertSchemaToCommonModel(...)`.

I have also changed the PR description, so it reflects the implementation.

2022-10-07 12:05 UTC, jonaslagoni requested changes
Just have one comment 🙂

2022-10-07 14:03 UTC, artur-ciocanu commented on src/models/ProcessorOptions.ts
> +import { InterpreterOptions } from 'interpreter/Interpreter';
Good call. Fixed.

2022-10-07 14:11 UTC, artur-ciocanu commented
@jonaslagoni I have addressed your comment. Please let me know if everything is looking good. Thank you!

2022-10-07 14:13 UTC, jonaslagoni approved these changes
LGTM 👍 

Changing the title to `fix` because this actually enables options to be passed along from the generators, so it's not so much a refactor 🙂

2022-10-07 14:14 UTC, jonaslagoni commented
/rtm

2022-10-07 14:14 UTC, merged